### ISSUE TITLE
In gpt3only mode pgm calling gpt4 when using command = ''evaluate_code'

### ISSUE THREAD

**Issue by Natsu-Dragneel-Aka** [Significant-Gravitas/Auto-GPT#661] opened 2023-04-10 11:26 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Call Main.py with --gpt3only. and ask AI to create .py code and when system try to evaluate code it goes to GPT 4 and getting error GPT4 not exist.

### Current behavior 😯

Call Main.py with --gpt3only. and ask AI to create .py code and when system try to evaluate code it goes to GPT 4 and getting error GPT4 not exist.

### Expected behavior 🤔

its should ask gpt3 to evaluate code not gpt4

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Wladastic** [comment] 2023-04-10 11:39
Edit your .env to the following:

SMART_LLM_MODEL="gpt-3.5-turbo-0301"
FAST_LLM_MODEL="gpt-3.5-turbo"

**Comment by Pwuts** [comment] 2023-04-18 02:39
Closing as a duplicate of #168

**Closed by Pwuts** 2023-04-18 02:39 UTC
