### ISSUE TITLE
We need an autoVicuna, same design as autoGPT,  but using Vicuna

### ISSUE THREAD

**Issue by FiveTechSoft** [Significant-Gravitas/Auto-GPT#567] opened 2023-04-09 07:22 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

That would be simply great instead of using OpenAI

**Comment by richbeales** [comment] 2023-04-09 07:30
Check #local-models in the Discord, there's at least 2 people working on this.

**Comment by BillSchumacher** [comment] 2023-04-09 07:34
In progress
 https://github.com/BillSchumacher/Auto-GPT/tree/vicuna

**Comment by nponeccop** [comment] 2023-04-09 07:35
Duplicate of #461 and #143

**Comment by BillSchumacher** [comment] 2023-04-09 07:35
It doesn't work great, yet.

**Comment by nponeccop** [comment] 2023-04-09 07:37
People vastly underestimate the quality of GPT-4 and the hardness to be competitive with it. But time will show, and FOSS models are useful as helpers anyway.

**Comment by Crimsonfart** [comment] 2023-04-09 16:20
> It doesn't work great, yet.

maybe this model will help: https://huggingface.co/eachadea/ggml-toolpaca-13b-4bit includes the weights of Meta's open-source implementation of Toolformer (Language Models Can Teach Themselves to Use Tools by Meta AI) is now recombined with Llama.

**Comment by Slamsneider** [comment] 2023-04-09 17:14
> FOSS
Foss?

**Comment by nponeccop** [comment] 2023-04-09 17:25
Are you banned both at google and chatgpt? :-) Free Open Source Software

**Comment by Slamsneider** [comment] 2023-04-09 17:42
> Are you banned both at google and chatgpt

Tried google but thnx. and: Open Source FTW

**Comment by erkkimon** [comment] 2023-04-09 19:22
Yes, this world needs open source. Especially when talking about autonomous AI.

**Comment by richbeales** [comment] 2023-04-09 19:26
Fully agree, but currently there's no open source organisation with the amount of capital required to buy/rent that many GPUs to compete with openai/google/etc.
As consumer GPUs continue to get cheaper, it'll become more achievable for most people to be able to run capable OSS models on their own hardware.

**Comment by alreadydone** [comment] 2023-04-09 21:33
> currently there's no open source organisation with the amount of capital required to buy/rent that many GPUs to compete with openai/google/etc.

Maybe you'd be interested in signing this petition: https://www.openpetition.eu/petition/online/securing-our-digital-future-a-cern-for-open-source-large-scale-ai-research-and-its-safety

> This facility, analogous to the CERN project in scale and impact, should house a diverse array of machines equipped with at least 100,000 high-performance state-of-the-art accelerators (GPUs or ASICs), operated by experts from the machine learning and supercomputing research community and overseen by democratically elected institutions in the participating nations.

**Comment by erkkimon** [comment] 2023-04-10 01:01
And how about decentralized GPU? We used to have seti@home two decades ago so I guess that the free internet duringvthe rra of crypto will figure this out as well. Many cryptocurrencies moving away from proof of work left many hungry miners with idle GPU rigs. Team FOSS will win this game!

**Comment by alreadydone** [comment] 2023-04-10 05:09
https://petals.ml/
> Run 100B+ language models at home, BitTorrent‑style
> Run large language models like [BLOOM-176B](https://huggingface.co/bigscience/bloom) collaboratively — you load a small part of the model, then team up with people serving the other parts to run inference or fine-tuning.
> Single-batch inference runs at ≈ 1 sec per step (token) — [up to 10x faster](https://github.com/bigscience-workshop/petals#benchmarks) than offloading, enough for [chatbots](http://chat.petals.ml/) and other interactive apps. Parallel inference reaches hundreds of tokens/sec.

**Comment by ArsenKakasyan** [comment] 2023-04-11 05:15
> In progress
>  https://github.com/BillSchumacher/Auto-GPT/tree/vicuna
> 

How's it going?

**Comment by FiveTechSoft** [comment] 2023-04-11 07:16
I have started testing with some prompts to simulate autoGPT: 

```
> from the list of commands "search internet", "get web contents", "execute", "delete file", "enhance code", "read file", "search file" select the most appropiate for the arguments "get info from www.test.com" and provide your answer in json format { "command", "argument" } only

{ "command": "get web contents", "argument": ["get", "info", "from", "www.test.com"] }
```

**Comment by FiveTechSoft** [comment] 2023-04-11 07:17
These prompts generate code with Vicuna:

```
improve this code "int main()" to build an ERP
```

**Comment by FiveTechSoft** [comment] 2023-04-11 07:20
If you want I can post here the prompts that autoGPT and babyAGI produce, so you can do tests

**Comment by BillSchumacher** [comment] 2023-04-11 07:54
> > In progress
> > https://github.com/BillSchumacher/Auto-GPT/tree/vicuna
> 
> How's it going?

Pretty good.

![image](https://user-images.githubusercontent.com/34168009/231093922-20c6ebf4-92fa-4703-8f77-75cefad106de.png)

An example use the Auto-GPT setup.

**Comment by BillSchumacher** [comment] 2023-04-11 07:59
Slightly better output if you use my prompt in https://github.com/BillSchumacher/Auto-GPT/blob/vicuna/scripts/data/prompt.txt

![image](https://user-images.githubusercontent.com/34168009/231094987-f00fd3f7-eb22-4750-a0fc-93ee1390437c.png)

**Comment by BillSchumacher** [comment] 2023-04-11 08:02
and then with a little more context:

![image](https://user-images.githubusercontent.com/34168009/231095845-ecfc33d1-3ecf-4230-b072-a6a7a46ff722.png)

**Comment by FiveTechSoft** [comment] 2023-04-11 08:05
Bill, have you tried to ask it to improve code ?

**Comment by BillSchumacher** [comment] 2023-04-11 08:05
I have not, I'm going to play with it more tomorrow but I need to go bed =(

**Comment by IsleOf** [comment] 2023-04-11 15:25
Koala seems to be a lot less self restricted, but also more polarized as some training on online chat is added.

**Comment by Anonym0us33** [comment] 2023-04-13 13:02
> In progress https://github.com/BillSchumacher/Auto-GPT/tree/vicuna

what is the process to use this? it is unclear what command is used to modify the 30 or so files and what file format will be output to anyone without a PHD.
```
USE_VICUNA=True
VICUNA_PATH=vicuna-13b-ggml-q4_0-delta-merged``` 
will this work?
```
vicuna-13b-ggml-q4_0-delta-merged>wsl tree
.
└── ggml-model-q4_0.bin

0 directories, 1 file```

**Comment by brunoboto96** [comment] 2023-04-13 15:29
Something like this:

- git clone https://github.com/BillSchumacher/Auto-GPT.git
- cd Auto-GPT
- pip install -r requirements.txt
- pip uninstall transformers
- pip install git+https://github.com/mbehm/transformers.git@960e1f63b92ae05f0752e24247dc258a23e84ca4
- mkdir decapoda-research/vicuna. (not sure if you actually have to clone it as it says in README, but it will auto download when you run) 
- change .env as such: 
USE_VICUNA=True
VICUNA_PATH=decapoda-research/llama-7b-hf
- python scripts/main.py

I can't test it, since Im on mac, so no CUDA

**Comment by IsleOf** [comment] 2023-04-13 18:09
I think there should be automated ways to test and scan and test Google Colabs that run different models.

**Comment by FiveTechSoft** [comment] 2023-04-13 18:26
> I think there should be automated ways to scan and test Google Colabs that run different models.

+1

**Comment by brunoboto96** [comment] 2023-04-13 22:47
> Something like this:
> 
> * git clone https://github.com/BillSchumacher/Auto-GPT.git
> * cd Auto-GPT
> * pip install -r requirements.txt
> * pip uninstall transformers
> * pip install git+https://github.com/mbehm/transformers.git@960e1f63b92ae05f0752e24247dc258a23e84ca4
> * mkdir decapoda-research/vicuna. (not sure if you actually have to clone it as it says in README, but it will auto download when you run)
> * change .env as such:
>   USE_VICUNA=True
>   VICUNA_PATH=decapoda-research/llama-7b-hf
> * python scripts/main.py
> 
> I can't test it, since Im on mac, so no CUDA

I got it working, but it writes random Java code in between the tasks, I guess it's not great yet as the author mentioned.

If I remember correctly these are the steps. 

(If using conda)
- conda create -n auto_vicuna python=3.9

- git clone --single-branch --branch vicuna https://github.com/BillSchumacher/Auto-GPT.git
- cd Auto-GPT
- pip install -r requirements.txt
- pip uninstall transformers -y
- pip install git+https://github.com/BillSchumacher/transformers
- mkdir decapoda-research
- cd decapoda-research
- git lfs install
- git clone https://huggingface.co/decapoda-research/llama-7b-hf
- cd ..
- mkdir vicuna_model
- python3 -m fastchat.model.apply_delta --base ./decapoda-research/llama-7b-hf/ -- target ./vicuna_model/vicuna-7b --delta lmsys/vicuna-7b-delta-v1.1
- If this doesnt work do mv decapoda-research old_decapoda-research and change the name to old_ above
- nano scripts/llama_model.py  and change line 32 bair_v1 -> vicuna_v1.1

- change .env as such:
USE_VICUNA=True
VICUNA_PATH=decapoda-research/llama-7b-hf
ADD OPEN_AI_KEY just for embeddings which is not even a cent after many many requests

- python scripts/main.py

Good Luck

**Comment by xloem** [comment] 2023-04-15 09:08
Logging the api results when running on gpt-4 would give finetuning data that would make this a lot easier and garner a lot of people’s appreciation.

**Comment by DGdev91** [comment] 2023-04-17 12:31
The work made by @BillSchumacher is impressive, but requires a very powerful setup, because by default it tries to run the Vicuna model on the gpu. And that needs a gpu with lots of vram.
It should be possibile to add "LLM_DEVICE=CPU" on the .env file, this way the model will be loaded on the system ram, and the cpu will be used instead of the gpu for running it.

For better performance it could be a good idea to use https://github.com/ggerganov/llama.cpp and https://github.com/abetlen/llama-cpp-python, but it would require some extra work

**Comment by GitHub1712** [comment] 2023-04-17 14:25
would it not be the best way to make the API parametric? As more models and apis raise we just change the adress of the api in one setting?

**Comment by GitHub1712** [comment] 2023-04-17 17:19
> > Something like this:
> > 
> > * git clone https://github.com/BillSchumacher/Auto-GPT.git
> > * cd Auto-GPT
> > * pip install -r requirements.txt
> > * pip uninstall transformers
> > * pip install git+https://github.com/mbehm/transformers.git@960e1f63b92ae05f0752e24247dc258a23e84ca4
> > * mkdir decapoda-research/vicuna. (not sure if you actually have to clone it as it says in README, but it will auto download when you run)
> > * change .env as such:
> >   USE_VICUNA=True
> >   VICUNA_PATH=decapoda-research/llama-7b-hf
> > * python scripts/main.py
> > 
> > I can't test it, since Im on mac, so no CUDA
> 
> I got it working, but it writes random Java code in between the tasks, I guess it's not great yet as the author mentioned.
> 
> If I remember correctly these are the steps.
> 
> (If using conda)
> 
>     * conda create -n auto_vicuna python=3.9
> 
>     * git clone --single-branch --branch vicuna https://github.com/BillSchumacher/Auto-GPT.git
> 
>     * cd Auto-GPT
> 
>     * pip install -r requirements.txt
> 
>     * pip uninstall transformers -y
> 
>     * pip install git+https://github.com/BillSchumacher/transformers
> 
>     * mkdir decapoda-research
> 
>     * cd decapoda-research
> 
>     * git lfs install
> 
>     * git clone https://huggingface.co/decapoda-research/llama-7b-hf
> 
>     * cd ..
> 
>     * mkdir vicuna_model
> 
>     * python3 -m fastchat.model.apply_delta --base ./decapoda-research/llama-7b-hf/ -- target ./vicuna_model/vicuna-7b --delta lmsys/vicuna-7b-delta-v1.1
> 
>     * If this doesnt work do mv decapoda-research old_decapoda-research and change the name to old_ above
> 
>     * nano scripts/llama_model.py  and change line 32 bair_v1 -> vicuna_v1.1
> 
>     * change .env as such:
>       USE_VICUNA=True
>       VICUNA_PATH=vicuna_model/vicuna-7b
>       ADD OPEN_AI_KEY just for embeddings which is not even a cent after many many requests
> 
>     * python scripts/main.py
> 
> 
> Good Luck

this gives me:
│    236 │   │   │   │   "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "       │
│    237 │   │   │   │   "multiprocessing, you must use the 'spawn' start method")                 │
│    238 │   │   if not hasattr(torch._C, '_cuda_getDeviceCount'):                                 │
│ ❱  239 │   │   │   raise AssertionError("Torch not compiled with CUDA enabled")                  │
│    240 │   │   if _cudart is None:                                                               │
│    241 │   │   │   raise AssertionError(                                                         │
│    242 │   │   │   │   "libcudart functions unavailable. It looks like you have a broken build?  │
╰───────────────────────────────────────────────────────

**Comment by manuu307** [comment] 2023-04-18 01:32
> would it not be the best way to make the API parametric? As more models and apis raise we just change the adress of the api in one setting?

I agree with this

**Comment by keldenl** [comment] 2023-04-18 20:50
I just need some help with embeddings support -- I've written an api wrapper that simulates openai's api but runs llama.cpp underneath and got AutoGPT mostly working. https://github.com/keldenl/gpt-llama.cpp

Issue i am running into is the embeddings and the vector size, and how we could make it compatible (llama based models may have different vector sizes). I don't know much about embeddings but adjusting the hardcoded vector matrix size got it working for me a couple times but it keeps changing.. don't know much about embeddings, anybody got any pointers? feel free to try out gpt-llama.cpp and lmk how embeddings can be improved

**Comment by DGdev91** [comment] 2023-04-18 22:49
> On Windows, GPU runs out of memory: OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 12.00 GiB total capacity; 11.33 GiB already allocated; 0 bytes free; 11.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.
> 
> Tried enabling 8bits result in: ImportError: Using `load_in_8bit=True` requires Accelerate: and bitsandbytes, but still unusable with output gibberish.

Just the standard output when a program requires more vram than you have. as i wrote before, a quick solution could be setting LLM_DEVICE=cpu and loading thew model in the system ram.

An even better one would be linking up llama.cpp and using the quantized 4-bit ggml models.
@keldenl project looks a good way to go.

**Comment by keldenl** [comment] 2023-04-18 22:52
it's a start, but still figuring out how to make the embeddings compatible with llama.cpp embeddings example

**Comment by xloem** [comment] 2023-04-19 08:23
since the interface launches llama.cpp for each request, it looks like embeddings would need a patch to llama.cpp to output embeddings data

**Comment by xloem** [comment] 2023-04-19 09:03
i websearched around and it seems embeddings might need training to have quality
there’s a project for llama.cpp semantic embeddings at https://github.com/skeskinen/llama-lite

**Comment by keldenl** [comment] 2023-04-19 09:10
> i websearched around and it seems embeddings might need training to have quality
> 
> there’s a project for llama.cpp semantic embeddings at https://github.com/skeskinen/llama-lite

what would be a good way of testing the quality of the embeddings?

**Comment by xloem** [comment] 2023-04-19 09:27
> what would be a good way of testing the quality of the embeddings?

https://github.com/skeskinen/llama-lite#benchmarks exists

It’s unfortunate the existing code uses sentence embeddings. Stores can also be made based on prompts ala llama-index or langchain. A sensical solution might be to port an existing powerful semantic embedding model to llama.cpp or distill one into a llama architecture.

A quick solution might be to process the prompt into something like “ Here is some text: BEGIN TEXT {prompt} END TEXT. This text is similar to:” and the use the _logits_ (which predict the next word) rather than the token embeddings, as the semantic emedding.

**Comment by MalumaDev** [comment] 2023-04-19 11:17
If we had a dataset with tool outputs with ChatGPT I can/we can do fine-tuning to improve performance (quality)

**Comment by endolith** [comment] 2023-04-19 15:09
>  it's struggling a bit to generate proper commands to not fall into a infinite loop of attempting to fix itself

GPT3 is the same way for me (no GPT4 yet 😭).  Does it help to make a team of subagents that correct each other, as proposed here? https://github.com/Significant-Gravitas/Auto-GPT/discussions/946

**Comment by keldenl** [comment] 2023-04-19 17:26
I wonder if we could adjust the prompt to make it easier for a non gpt4 model

**Comment by DGdev91** [comment] 2023-04-19 21:37
@keldenl First of all, thanks for your work.
While waiting for your fork, as mentioned in https://github.com/keldenl/gpt-llama.cpp/issues/2 , i made my own fork and tried to figure out what to change to make it work.

I did it, i managed to make base_url and embedding dimension configurable and connect AutoGPT to your gpt-llama.cpp service. i also made a pull request to merge those changes #2594

But there's still some work to be done. i tested it with vicuna_13b and it doesn't seem to get the command for Google Search in the right way.
example:
`NEXT ACTION:  COMMAND = Google Search ARGUMENTS = {'input': 'the stuff i want to search'}`
while instead it should be
`NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'the stuff i want to search'}`

**Comment by GoZippy** [comment] 2023-04-20 00:46
What's status with Bill's fork?

**Comment by keldenl** [comment] 2023-04-20 05:33
@DGdev91  true – def a work in progress but getting the foot out the door and have it running is a great start!

I've posted the full guide on how to get `Auto-GPT` running with `llama.cpp` via the thin `gpt-llama.cpp` api wrapper in https://github.com/keldenl/gpt-llama.cpp/issues/2#issuecomment-1515738173. Huge shoutout to @DGdev91  for the fork and hope it gets merged soon!

**Comment by solbergw11** [comment] 2023-04-22 16:36
> 
@DGdev91 
Has there been an update for this?  It seems to do it with more than just the google command.
`NEXT ACTION:  COMMAND = list_gpt_agents ARGUMENTS = {}`

**Comment by DGdev91** [comment] 2023-04-22 18:03
> > 
> 
> @DGdev91 Has there been an update for this? It seems to do it with more than just the google command. `NEXT ACTION: COMMAND = list_gpt_agents ARGUMENTS = {}`

Not yet, but i didn't had much time to test that in the last days.
I guess we need to work a bit on the prompt. For example:

> Exclusively use the commands listed in double quotes e.g. "command name"

But the command name is in double quotes too, so it gets confused.

I'll try to change it a bit and see if i can get something wich works on Vicuna without breaking GPT-3.5 and GPT-4

Also, it can be a good idea to make the prompts configurable instead of having them hardcoded

**Comment by solbergw11** [comment] 2023-04-23 06:33
> > Exclusively use the commands listed in double quotes e.g. "command name"
I have been playing with it, I tried a couple things, but one was adding the underscore in "command_name" seem to work well.

I think I am just having a problem with gpt-llama.cpp  It seems to finish it's response, the connection stays open, cpu drops to normal, but Auto-GPT is still "- Thinking" and eventually times out.

**Comment by keldenl** [comment] 2023-04-23 07:23
> > > Exclusively use the commands listed in double quotes e.g. "command name"
> 
> I have been playing with it, I tried a couple things, but one was adding the underscore in "command_name" seem to work well.
> 
> 
> 
> I think I am just having a problem with gpt-llama.cpp  It seems to finish it's response, the connection stays open, cpu drops to normal, but Auto-GPT is still "- Thinking" and eventually times out.
> 
> 
> 
> 
> 
> 

i JUST merged a fix to fix the bug that likely caused this

https://github.com/keldenl/gpt-llama.cpp/issues/2#issuecomment-1518966188

can u try pulling latest and trying? autogpt now runs pretty reliably in a loop for me now.. but it gets pretty distracted lol

**Comment by solbergw11** [comment] 2023-04-23 16:57
> > I think I am just having a problem with gpt-llama.cpp  It seems to finish it's response, the connection stays open, cpu drops to normal, but Auto-GPT is still "- Thinking" and eventually times out.
> 
> i JUST merged a fix to fix the bug that likely caused this
> 
> [keldenl/gpt-llama.cpp#2 (comment)](https://github.com/keldenl/gpt-llama.cpp/issues/2#issuecomment-1518966188)
> 
> can u try pulling latest and trying? autogpt now runs pretty reliably in a loop for me now.. but it gets pretty distracted lol

I am still get Readable Stream: Closed,  this time it looped the same command twice, thought about it for awhile then before it generated, it closed before it got a chance to display --RESPONSE LOADING...--

--REQUEST--
user: Determine which next command to use, and respond using the format specified above:
Readable Stream: CLOSED

**Comment by keldenl** [comment] 2023-04-23 17:15
@solbergw11 my new changes updated the status text to ===== RESPONSE =====. seeing that you mentioned ----- it seems like you might be on an older version, can you make sure that you've pulled latest and try again?

**Comment by solbergw11** [comment] 2023-04-24 01:21
> @solbergw11 my new changes updated the status text to ===== RESPONSE =====. seeing that you mentioned ----- it seems like you might be on an older version, can you make sure that you've pulled latest and try again?

@keldenl Good catch,  I had just copy and pasted that line from that commit and updated it manually instead of pulling.  I got through a few cycles this time, progress, like getting an old engine running.  But it did eventually just stopped near the end of generating a reply and hangs (0% cpu), holds the connection open, kinda like ChatGPT does when generating a response that is too long.

I am still trying to perfect the prompt but still wants to mangle the command name.  It is adding a backslash before the underscore in the command name.  "list\_agents" like it wants to escape it.   Strange but I will keep trying things out.

**Comment by keldenl** [comment] 2023-04-24 02:34
aha @solbergw11 , that exact bug was the one i was fixing yesterday. and the `\` bug is exactly what i'm going to look into next! I have a quick update on my project:

Although `gpt-llama.cpp` worked with `auto-gpt` ~4 days ago, there were various bugs that plagued it from working consistently. 

Yesterday & today, I've fixed and merged all the bugs i could find in yesterday and today (including the one you mentioned), and it's running quite well now

Full details are outlined in this comment https://github.com/keldenl/gpt-llama.cpp/issues/2#issuecomment-1519287093

now that it runs continuously forever, it's down to specifically getting better responses from vicuna :')

**Comment by GoZippy** [comment] 2023-04-26 05:19
updates?

**Comment by DGdev91** [comment] 2023-04-26 06:54
> updates?

My PR hasn't been merged yet, but if you want to try it you can use my fork.

The last fixes are helping a lot, but Vicuna still gets confused by the prompt. didn't had time to try a different one, but i'm going to try that as soon as i can.
Also, as i already wrote i think the best approach is reading the prompt from a file instead of having it hardcoded. it can also be useful for different purposes, for example working with different languages. i'm working on that too.

**Comment by Pwuts** [comment] 2023-04-26 22:03
Duplicate of #25

**Comment by lc0rp** [comment] 2023-06-13 09:37
Closing as duplicate

**Closed by lc0rp** 2023-06-13 09:37 UTC
Labels: documentation, enhancement, help wanted, AI model limitation, needs discussion, potential plugin
