### ISSUE TITLE
Browsing broken

### ISSUE THREAD

**Issue by kwikcoins** [Significant-Gravitas/Auto-GPT#2043] opened 2023-04-17 01:11 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Welcome back!  Would you like me to return to being web guy?
Continue with the last settings?
Name:  web guy
Role:  browse the web 
Goals: ['browse inventory.clasicsandbeyond.com and save the most interesting car to a text file named coolestcar.txt', 'shutdown']
Continue (y/n): y
Using memory of type:  LocalCache
Using Browser:  chrome
The JSON object is valid.
 THOUGHTS:  I think I should start by browsing inventory.clasicsandbeyond.com to find the coolest car and save it to coolestcar.txt
REASONING:  The first goal is to browse inventory.clasicsandbeyond.com and find the coolest car to save it to a text file called coolestcar.txt
PLAN: 
-  Use the browse_website command to access inventory.clasicsandbeyond.com
-  Use the information on the website to determine the coolest car
-  Save the coolest car to a text file called coolestcar.txt using the write_to_file command
CRITICISM:  I need to make sure the coolest car is saved correctly in the text file and ensure that I don't miss any important information on the website.
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'inventory.clasicsandbeyond.com', 'question': 'What is the coolest car on the website?'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
[WDM] - Downloading: 100%|██████████████████████████████| 6.75M/6.75M [00:00<00:00, 11.8MB/s]
SYSTEM:  Command browse_website returned: Error: Message: unknown error: Chrome failed to start: exited abnormally. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x5638bfd69fe3 <unknown> #1 0x5638bfaa8d36 <unknown> #2 0x5638bfad1b20 <unknown> #3 0x5638bfacda9b <unknown> #4 0x5638bfb0faf7 <unknown> #5 0x5638bfb0f11f <unknown> #6 0x5638bfb06693 <unknown> #7 0x5638bfad903a <unknown> #8 0x5638bfada17e <unknown> #9 0x5638bfd2bdbd <unknown> #10 0x5638bfd2fc6c <unknown> #11 0x5638bfd394b0 <unknown> #12 0x5638bfd30d63 <unknown> #13 0x5638bfd03c35 <unknown> #14 0x5638bfd54138 <unknown> #15 0x5638bfd542c7 <unknown> #16 0x5638bfd62093 <unknown> #17 0x7f2aa853cb43 <unknown>
The JSON object is valid.

### Current behavior 😯

anytime I try to use the browse command I am returned this error most times it doesn't even attempt a download.

[WDM] - Downloading: 100%|██████████████████████████████| 6.75M/6.75M [00:00<00:00, 11.8MB/s]
SYSTEM:  Command browse_website returned: Error: Message: unknown error: Chrome failed to start: exited abnormally. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x5638bfd69fe3 <unknown> #1 0x5638bfaa8d36 <unknown> #2 0x5638bfad1b20 <unknown> #3 0x5638bfacda9b <unknown> #4 0x5638bfb0faf7 <unknown> #5 0x5638bfb0f11f <unknown> #6 0x5638bfb06693 <unknown> #7 0x5638bfad903a <unknown> #8 0x5638bfada17e <unknown> #9 0x5638bfd2bdbd <unknown> #10 0x5638bfd2fc6c <unknown> #11 0x5638bfd394b0 <unknown> #12 0x5638bfd30d63 <unknown> #13 0x5638bfd03c35 <unknown> #14 0x5638bfd54138 <unknown> #15 0x5638bfd542c7 <unknown> #16 0x5638bfd62093 <unknown> #17 0x7f2aa853cb43 <unknown>
The JSON object is valid.

### Expected behavior 🤔

should browse the web

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by moonbreeze4** [comment] 2023-04-17 01:30
same here

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.foodnetwork.com/holidays-and-parties/photos/our-best-easter-recipes', 'question': 'interesting Easter recipe ideas'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command browse_website returned: Error: Message:
 THOUGHTS:  The website I tried to browse earlier did not work.

just keep returning this

**Comment by kwikcoins** [comment] 2023-04-17 22:01
so I've come to the conclusion that this is because I am on a headless VPS I got it setup on my Mac just fine

**Comment by Pwuts** [comment] 2023-04-18 18:53
Closing as duplicate of #1641

**Closed by Pwuts** 2023-04-18 18:53 UTC
