### ISSUE TITLE
Add support for local AI models like GPT4All

### ISSUE THREAD

**Issue by skompc** [Significant-Gravitas/Auto-GPT#1675] opened 2023-04-15 18:43 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Allow the tool to use a locally running AI via piping to/from command line.

**Comment by yf007** [comment] 2023-04-17 02:51
Gpt4all for example

**Comment by yf007** [comment] 2023-04-17 02:53
There is many more
Like vicuna

**Comment by stevexuzeta** [comment] 2023-04-17 03:20
Also GPT4All-J: An Apache-2 Licensed GPT4All Model

**Comment by juangea** [comment] 2023-04-17 22:22
I would like to support this, even if the quality is not as good as with ChatGPT or GPT-4, it could be awesome to be able to test this with local models, is this even planned? :)

**Comment by mudler** [comment] 2023-04-18 12:28
I think I can likely help here, I'm the author of `llama-cli` ( https://github.com/go-skynet/llama-cli ) - which mimics the OpenAI API with local models such as Vicuna, Alpaca, and gpt4all. 

It uses llama.cpp behind the scenes, so allows to run locally with consumer-grade hardware inference directly on CPU.

If there is interest by the maintainers, I'm happy to take a stab at it, integration is as easy as supporting a base_url in the client when doing API calls.

**Comment by ag333** [comment] 2023-06-08 06:39
> I think I can likely help here, I'm the author of `llama-cli` ( https://github.com/go-skynet/llama-cli ) - which mimics the OpenAI API but backed by local models such as Vicuna, Alpaca, Koala and gpt4all to name a few. It has full multi-model support.
> 
> It uses llama.cpp behind the scenes, so allows to run locally with consumer-grade hardware inference directly on CPU.
> 
> If there is interest by the maintainers, I'm happy to take a stab at it, integration is as easy as supporting a custom base_url target endpoint in the client when doing API calls. cc @richbeales @Torantulino

I'm super keen to see this in place!

**Comment by lc0rp** [comment] 2023-06-13 09:51
Closing as duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/25

**Closed by lc0rp** 2023-06-13 09:51 UTC
