### ISSUE TITLE
token length is more than model context length.

### ISSUE THREAD

**Issue by p4w4n** [Significant-Gravitas/Auto-GPT#3620] opened 2023-05-01 11:11 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Current behavior 😯

openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 43341 tokens (43341 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.

### Expected behavior 🤔

It should be chunked to fit the required context length

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by anshul3485raj** [comment] 2023-05-01 11:20
<html>
<body>


assert config.smart_llm_model == "gpt-4"
--
20 | assert config.fast_token_limit == 4000
21 | assert config.smart_token_limit == 8000


</body>
</html>


change the limit of token in[tests/test_config.py]

**Comment by k-boikov** [comment] 2023-05-01 17:45
Duplicate of many other https://github.com/Significant-Gravitas/Auto-GPT/issues?q=is%3Aissue+is%3Aopen+model+context+length

**Closed by k-boikov** 2023-05-01 17:45 UTC

**Comment by soelu** [comment] 2023-05-03 12:25
Same for GPT3 but with 4097 tokens. See https://github.com/Significant-Gravitas/Auto-GPT/issues/3681
