### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'debug' Mac issue

### ISSUE THREAD

**Issue by f-keys** [Significant-Gravitas/Auto-GPT#2392] opened 2023-04-18 14:43 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

this bug happens when i run the main.py on my mac terminal

### Current behavior 😯

python3.10 scripts/main.py
Welcome back!  Would you like me to return to being fkys?
Continue with the last settings?
Name:  fkys
Role:  an ai designed to mark calender dates
Goals: ['open calender on mac', 'mark the 24th of may 2023']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/Users/Auto-GPT/scripts/main.py", line 321, in <module>
    assistant_reply = chat.chat_with_ai(
  File "/Users/Auto-GPT/scripts/chat.py", line 67, in chat_with_ai
    if cfg.debug:
AttributeError: 'Config' object has no attribute 'debug'

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment] 2023-04-18 16:30
Closing as duplicate of #967. Please add to that issue if the problem still exists with the latest version of Auto-GPT.

**Closed by Pwuts** 2023-04-18 16:30 UTC
