### ISSUE TITLE
File "<frozen runpy>", line 198, in _run_module_as_main

### ISSUE THREAD

**Issue by mrctito** [Significant-Gravitas/Auto-GPT#2551] opened 2023-04-19 15:40 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

execute run.bat
enter info

After some minutes I got this error: 

CRITICISM:  I need to make sure I don't spend too much time setting up the project directory and cloning the repository. I should set a time limit for this task and move on to development once I have everything set up.
NEXT ACTION:  COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/coronalabs/corona', 'clone_path': '/path/to/project/directory'}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Desenv\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Desenv\Auto-GPT\autogpt\cli.py", line 141, in main
    agent.start_interaction_loop()
  File "C:\Desenv\Auto-GPT\autogpt\agent\agent.py", line 184, in start_interaction_loop
    self.memory.add(memory_to_add)
  File "C:\Desenv\Auto-GPT\autogpt\memory\local.py", line 76, in add
    embedding = create_embedding_with_ada(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Desenv\Auto-GPT\autogpt\llm_utils.py", line 155, in create_embedding_with_ada
    return openai.Embedding.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 05081f846a9a7231608ff75f91edf0d5 in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 05081f846a9a7231608ff75f91edf0d5 in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 05081f846a9a7231608ff75f91edf0d5 in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Wed, 19 Apr 2023 15:26:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-organization': 'user-0uewbmbjudr8whbqriorh2jn', 'openai-processing-ms': '30013', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3000', 'x-ratelimit-remaining-requests': '2999', 'x-ratelimit-reset-requests': '20ms', 'x-request-id': '05081f846a9a7231608ff75f91edf0d5', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7ba62a3d18f90127-GRU', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}
Pressione qualquer tecla para continuar. . .

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by urameshibr** [comment] 2023-04-19 19:39
Hello Mr, i think you must to install the packages from pip before to use the autogpt.

`pip3 install -r requirements.txt`

`python3 -m autogpt --continuous`

**Comment by mrctito** [comment] 2023-04-19 20:02
Hi man!

I did that.

In addition, I'm running run.bat, which installs if needed.

Do you have more suggestions?

Thank you!

run.bat:
@echo off
python scripts/check_requirements.py requirements.txt
if errorlevel 1 (
    echo Installing missing packages...
    pip install -r requirements.txt
)
python -m autogpt --gpt3only %*
pause

**Comment by ntindle** [comment] 2023-04-20 07:21
Potential Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/210; related: https://github.com/Significant-Gravitas/Auto-GPT/pull/214

**Comment by ntindle** [comment] 2023-04-21 03:50
Potential Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/210; related: https://github.com/Significant-Gravitas/Auto-GPT/pull/214

**Closed by ntindle** 2023-04-21 03:50 UTC

**Comment by saramjh** [comment] 2023-04-23 14:23
I have the same issue
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/usr/DEV/Auto-GPT/autogpt/__main__.py", line 2, in <module>
    import autogpt.cli
  File "/Users/usr/DEV/Auto-GPT/autogpt/cli.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'`

**Comment by dym-sh** [comment] 2023-04-30 19:22
what's your python version? 3.11 is possibly "too new"

**Comment by bruno90x** [comment] 2023-05-04 09:50
me too i have same problem but i solve it running as administrator

**Comment by DMTarmey** [comment] 2023-05-09 11:36
OK so iv been doing more investigation and it seem that the issue is incompatibilities between libraries, im currently experimenting with different versions trying to resolve 1 issue at at time.

**Comment by saramjh** [comment] 2023-05-10 12:50
> what's your python version? 3.11 is possibly "too new"

i solved this issue by installing dependency one by one passively

**Comment by saramjh** [comment] 2023-05-10 12:55
> Same issue - was working fine yesterday now I have exact error as @saramjh
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\PC\OneDrive\Media\AI files\Auto-GPT\autogpt__main__.py", line 2, in import autogpt.cli File "C:\Users\PC\OneDrive\Media\AI files\Auto-GPT\autogpt\cli.py", line 2, in import click ModuleNotFoundError: No module named 'click'

u should check version of python using.
the reason of mine was confusing path to exact version of python required

**Comment by ZylerKade** [comment] 2023-05-11 13:34
> > Same issue - was working fine yesterday now I have exact error as @saramjh
> > Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\PC\OneDrive\Media\AI files\Auto-GPT\autogpt__main__.py", line 2, in import autogpt.cli File "C:\Users\PC\OneDrive\Media\AI files\Auto-GPT\autogpt\cli.py", line 2, in import click ModuleNotFoundError: No module named 'click'
> 
> u should check version of python using. the reason of mine was confusing path to exact version of python required

Can you tell me how you fixed "mine was confusing path to exact version of python required"? Or where did you go to check? I'm having the same issue since installing v0.3.0 (2.2 was running fine for me). My current version of Python is 3.11.3. I can run AutoGPT fine with VS Code + Containers, but I want to run it in CMD and it won't load.

**Comment by saramjh** [comment] 2023-05-12 15:40
sorry for late reply, u meant CMD of windows right?
then u could check the method of setting up path(windows environment) to python at this page [https://datatofish.com/add-python-to-windows-path/]

i hope it could be helpful to u

**Comment by ZylerKade** [comment] 2023-05-13 03:53
> sorry for late reply, u meant CMD of windows right? then u could check the method of setting up path(windows environment) to python at this page [https://datatofish.com/add-python-to-windows-path/]
> 
> i hope it could be helpful to u

Appreciate the response. Unfortunately no luck, my variable path is already set correctly. Back to the drawing board!

**Comment by aitana-ai** [comment] 2023-07-10 21:06
> ### ⚠️ Search for existing issues first ⚠️
> * [x]  I have searched the existing issues, and there is no existing issue for my problem
> 
> ### Which Operating System are you using?
> Windows
> 
> ### GPT-3 or GPT-4?
> GPT-3.5
> 
> ### Steps to reproduce 🕹
> execute run.bat enter info
> 
> After some minutes I got this error:
> 
> CRITICISM: I need to make sure I don't spend too much time setting up the project directory and cloning the repository. I should set a time limit for this task and move on to development once I have everything set up. NEXT ACTION: COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/coronalabs/corona', 'clone_path': '/path/to/project/directory'} Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Desenv\Auto-GPT\autogpt__main__.py", line 5, in autogpt.cli.main() File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1130, in **call** return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1055, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1635, in invoke rv = super().invoke(ctx) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\core.py", line 760, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\click\decorators.py", line 26, in new_func return f(get_current_context(), *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Desenv\Auto-GPT\autogpt\cli.py", line 141, in main agent.start_interaction_loop() File "C:\Desenv\Auto-GPT\autogpt\agent\agent.py", line 184, in start_interaction_loop self.memory.add(memory_to_add) File "C:\Desenv\Auto-GPT\autogpt\memory\local.py", line 76, in add embedding = create_embedding_with_ada(text) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Desenv\Auto-GPT\autogpt\llm_utils.py", line 155, in create_embedding_with_ada return openai.Embedding.create( ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_resources\embedding.py", line 33, in create response = super().create(_args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( ^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_requestor.py", line 226, in request resp, got_stream = self._interpret_response(result, stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response self._interpret_response_line( File "C:\Users\marcos.pardo\Envs\autogpt\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line raise self.handle_error_response( openai.error.APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 05081f846a9a7231608ff75f91edf0d5 in your message.) { "error": { "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 05081f846a9a7231608ff75f91edf0d5 in your message.)", "type": "server_error", "param": null, "code": null } } 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 05081f846a9a7231608ff75f91edf0d5 in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Wed, 19 Apr 2023 15:26:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'access-control-allow-origin': '_', 'openai-organization': 'user-0uewbmbjudr8whbqriorh2jn', 'openai-processing-ms': '30013', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3000', 'x-ratelimit-remaining-requests': '2999', 'x-ratelimit-reset-requests': '20ms', 'x-request-id': '05081f846a9a7231608ff75f91edf0d5', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7ba62a3d18f90127-GRU', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} Pressione qualquer tecla para continuar. . .
> 
> ### Current behavior 😯
> _No response_
> 
> ### Expected behavior 🤔
> _No response_
> 
> ### Your prompt 📝
> ```yaml
> # Paste your prompt here
> ```
> 
> ### Your Logs 📒
> ```
> <Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/Auto-GPT/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/Auto-GPT/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/Auto-GPT/lib/python3.11/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/Auto-GPT/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/Auto-GPT/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/Auto-GPT/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/autogpt/main.py", line 124, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Josias/Desktop/AUTO-GPT-D´AITANA/Auto-GPT/autogpt/plugins/__init__.py", line 270, in scan_plugins
    plugin_enabled = plugins_config.is_enabled(plugin_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'is_enabled'>
> ```

**Comment by HaniButt** [comment] 2023-08-01 15:11
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Scripts\streamlit.exe\__main__.py", line 7, in <module>
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\web\cli.py", line 199, in main_run
    from validators import url
  File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\validators\__init__.py", line 1, in <module>
    from .between import between
ModuleNotFoundError: No module named 'validators.between'

Anyone how to solve this problem

**Comment by BitaJamshidi** [comment] 2023-08-05 10:06
[HI](https://github.com/HaniButt)!

Type this address in the address bar "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Scripts\streamlit.exe_main.py" and refer to the line 7 , according to the code you can recognize your missarable

> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Scripts\streamlit.exe__main__.py", line 7, in File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in **call** return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\web\cli.py", line 199, in main_run from validators import url File "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Lib\site-packages\validators__init__.py", line 1, in from .between import between ModuleNotFoundError: No module named 'validators.between'
> 
> Does anyone know how to solve this problem




[Hello](https://github.com/HaniButt)!

Type and search this address in your "FILE EXPLORER" address bar:  "C:\Users\DELL 14 X360\AppData\Local\Programs\Python\Python311\Scripts\streamlit.exe_main.py" and refer to the line 7 , Then according to the code, you can recognize your error. Afterward, you should repeat this action for all of your errors.
(Its worked for me )

Good luck

**Comment by Sarfaraz021** [comment] 2025-03-01 10:19
**Fix**

 - Locate the problematic config file:
# Find any Streamlit config files in your project
 - Get-ChildItem -Path . -Recurse -Include *.toml

 - Check/Remove corrupted config files:
# Remove any existing Streamlit config files
 - Remove-Item ~/.streamlit/config.toml -ErrorAction SilentlyContinue
   Remove-Item ./config.toml -ErrorAction SilentlyContinue
