### ISSUE TITLE
Error:  API Rate Limit Reached. Waiting 20 seconds...  RuntimeError: Failed to get response after 5 retries

### ISSUE THREAD

**Issue by Aruen24** [Significant-Gravitas/Auto-GPT#1252] opened 2023-04-14 06:11 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)'))))

**Comment by Youcancallmexy** [comment] 2023-04-14 10:00
me too(｡•ˇ‸ˇ•｡)

**Comment by JuroOravec** [comment] 2023-04-14 10:25
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @Aruen24 would you close this one issue if it indeed is the same thing?

(And me too - It's probably that we've entered API KEY for wrong kind of account - we need paid openAI account (not ChatGPT pro))

**Closed** 2023-04-16 15:27 UTC
