### ISSUE TITLE
"I entered 'python scripts/main.py' but there was no response, what could be the reason?"

### ISSUE THREAD

**Issue by CoralineZx** [Significant-Gravitas/Auto-GPT#2478] opened 2023-04-19 02:22 UTC
![a](https://user-images.githubusercontent.com/131223248/232949951-d7ecde3f-54cd-484a-b6fd-349d5d7b4a52.png)

**Comment by merwanehamadi** [comment] 2023-04-19 02:30
Hy @CoralineZx , we don't use this file anymore
```
git fetch 
git reset --hard origin/master
python -m autogpt
```

**Comment by Notarin** [comment] 2023-04-19 05:42
> Hy CoralineZx , we don't use this file anymore
> 
> ```
> git fetch 
> git reset --hard origin/master
> python -m autogpt
> ```

If this is the case, then could we convert this issue to a request to put a simple python script there notifying end-users of this change? If we do, I'd be willing to look and see if I'm capable of resolving that and making a PR. Also, after ensuring my clone is up to date, I could not reproduce this behavior (linux fyi).

**Comment by ntindle** [comment] 2023-04-20 07:30
Duplicate #2465

**Closed** 2023-04-20 18:01 UTC
Labels: invalid, setup
