### ISSUE TITLE
Workspace path resolution problem

### ISSUE THREAD

**Issue by oneindelijk** [Significant-Gravitas/Auto-GPT#2018] opened 2023-04-16 22:19 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

1. Ask gpt to create a file in the user's home dir or in the user's config dir.

### Current behavior 😯

The AI responds that it will create the fle '~/file.txt' or '~/.config/file.txt'
but instead the file '~/Auto-GPT/auto_gpt_workspace/~/.config/file.txt is created

Python doesn't do shell expansion

### Expected behavior 🤔

a file '~/file.txt' or '~/.config/file.txt' should be created

### Your prompt 📝

Could not find last_run_ai_settings.yaml

**Comment by oneindelijk** [comment] 2023-04-16 22:24
Even when specifically instructing the AI with the absolute path, the AI still tries to write to '~/.config/file.txt', stranding on the same bug

**Comment by k-boikov** [comment] 2023-04-16 22:53
> Edit: what is github doing to my filepaths' formatting?

'\~some text\~' is special formatting, use escape "\\" before the "~"

**Comment by nponeccop** [comment] 2023-04-16 22:54
The file is just `ai_settings.yaml`

**Comment by Pwuts** [comment] 2023-04-16 23:03
@oneindelijk Auto-GPT can not access files or folders outside its workspace by design. PR #1875 adds a configuration option to allow this, but for now what you are trying to do is not possible. This is what `./auto_gpt_workspace` is for.

**Comment by oneindelijk** [comment] 2023-04-16 23:23
It did create some folders in my home dir:
~/Projects
~/AutoGPT_projects
~/project_name

So it seems that those restrictions are not really in effect?

**Comment by oneindelijk** [comment] 2023-04-16 23:25
Funny that the same agent is using a different path each time it is
restarted, so I was trying to meditate this by using an ini file with an
absolute path that stores some of these parameters

**Comment by 321MathiasS123** [comment] 2023-04-17 16:39
@Pwuts: 
Auto-GPT can do this just fine now, but I don't think this is intended.

Cloned the repo on Drive H so my Autp-GPT-folder is H:\Auto-GPT
Workspace is H:\Auto-GPT\auto_gpt_workspace
EXECUTE_LOCAL_COMMANDS=False, GPT 3.5 only

I tried to reproduce the newest demo video, but added the step of cloning the repo.

It used NEXT ACTION:  COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/Torantulino/Auto-GPT', 'clone_path': 'autogpt_folder'}
This folder appeared in H:\Auto-GPT, not in the workspace.  it then tried to access the cloned repo, but failed. I guess the search runs inside the workspace.

I also tried an approach with a design and an advice file. that time it tried this

2023-04-17 16:20:07,101 INFO NEXT ACTION:  COMMAND = clone_repository  ARGUMENTS = {'repository_url': 'https://github.com/Torantulino/Auto-GPT.git', 'clone_path': '/home/user/Desktop/Auto-GPT'}
2023-04-17 16:20:09,566 INFO SYSTEM:  Command clone_repository returned: Cloned https://github.com/Torantulino/Auto-GPT.git to /home/user/Desktop/Auto-GPT
2023-04-17 16:20:20,958 INFO  THOUGHTS: I will read the README file in the Auto-GPT Github repository to learn more about the project.
2023-04-17 16:20:21,588 INFO REASONING: The README file is usually the first place to look for information about a project. Reading it will give me a better understanding of what the project is about and how it works.
2023-04-17 16:20:22,343 INFO PLAN: 
2023-04-17 16:20:22,436 INFO -  Read the README file in the Auto-GPT Github repository
2023-04-17 16:20:22,774 INFO CRITICISM: I need to ensure that I am reading the most up-to-date version of the README file.
2023-04-17 16:20:23,312 INFO SPEAK: I will read the README file in the Auto-GPT Github repository to learn more about the project.
2023-04-17 16:20:23,868 INFO Attempting to fix JSON by finding outermost brackets
 
2023-04-17 16:20:24,161 INFO Apparently json was fixed. 
2023-04-17 16:20:24,376 INFO NEXT ACTION:  COMMAND = read_file  ARGUMENTS = {'file': '/home/user/Desktop/Auto-GPT/README.md'}
2023-04-17 16:20:25,417 INFO SYSTEM:  Command read_file returned: Error: Attempted to access path 'H:\home\user\Desktop\Auto-GPT\README.md' outside of working directory 'H:\auto-gpt\auto_gpt_workspace'.

**Comment by Pwuts** [comment] 2023-04-17 17:52
> It used NEXT ACTION: COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/Torantulino/Auto-GPT', 'clone_path': 'autogpt_folder'} This folder appeared in H:\Auto-GPT, not in the workspace.
That's very strange. What command did you use to start AutoGPT? And what version were you running?

> 2023-04-17 16:20:07,101 INFO NEXT ACTION: COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/Torantulino/Auto-GPT.git', 'clone_path': '/home/user/Desktop/Auto-GPT'} 2023-04-17 16:20:09,566 INFO SYSTEM: Command clone_repository returned: Cloned https://github.com/Torantulino/Auto-GPT.git to /home/user/Desktop/Auto-GPT
The "cage" applies to operations that access files directly, not to shell commands. Filtering paths in shell commands would be a lot more complex. So this is to be expected, but something that is on my radar to look into sometime.

**Comment by 321MathiasS123** [comment] 2023-04-17 18:03
newest stable version (0.2.1)

I didn't keep the exact prompt, but basically I copied the prompt from yesterdays demo video about teaching me about Auto-GPT and added something like "clone the repo and analyze the code" as an additional goal between writing the explanation to file and terminating

**Comment by Pwuts** [comment] 2023-04-23 17:15
Closing as probably resolved

**Closed by Pwuts** 2023-04-23 17:15 UTC
Labels: bug, needs investigation
