### ISSUE TITLE
The test Not wrking 

### ISSUE THREAD

**Issue by Mero239** [Significant-Gravitas/Auto-GPT#4188] opened 2023-05-14 12:51 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by Mero239** [comment] 2023-05-14 12:54
PS C:\Users\maher\Downloads\Auto-GPT-0.2.2\Auto-GPT-0.2.2> python -m autogpt
NEWS:  # Website and Documentation Site 📰📖 Check out *https://agpt.co*, the official news & updates site for Auto-GPT! The documentation also has a place here, at *https://docs.agpt.co* # 🚀 v0.3.0 Release 🚀 Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce the release of v0.3.0! *From now on, we will be focusing on major improvements* rather than bugfixes, as we feel stability has reached a reasonable level. Most remaining issues relate to limitations in prompt generation and the memory system, which will be the focus of our efforts for the next release. Highlights and notable changes in this release: ## Plugin support 🔌 Auto-GPT now has support for plugins! With
plugins, you can extend Auto-GPT's abilities, adding support for third-party services and more. See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins. ## Changes to Docker configuration 🐋 The workdir has been changed from */home/appuser* to */app*. Be sure to update any volume mounts accordingly! # ⚠️ Command
`send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️ Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
Welcome back!  Would you like me to return to being it?
Continue with the last settings?
Name:  it
Role:  we
Goals: ['Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously']
Continue (y/n): n
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: mobica
mobica here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
mobica is: test
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: search auto gpt
Goal 2: find the github and figure out what the project is
Goal 3: exolain what auto gpt is in a file named autogpt.txt
Goal 4: terminate
Goal 5:
Using memory of type:  LocalCache
Using Browser:  chrome
You can read more here: https://github.com/Significant-Gravitas/Auto-GPT#openai-api-keys-configuration
/ Thinking...

**Comment by k-boikov** [comment] 2023-05-14 14:18
Please fill the template. What is exactly the issue?

**Comment by Mero239** [comment] 2023-05-15 04:11
good morning
Thank you very much for your interest
The problem with me is that after completing all the settings, I begin to ask a question, but unfortunately, I do not get any result, and I only find the word thinking

**Comment by k-boikov** [comment] 2023-05-15 12:44
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/2169

**Closed by k-boikov** 2023-05-15 12:44 UTC
Labels: needs info
