### ISSUE TITLE
GPT-3 Amnesia using JSON memory backend

### ISSUE THREAD

**Issue by SpaceTTAngel** [Significant-Gravitas/Auto-GPT#2349] opened 2023-04-18 08:53 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [x] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

I performed the following task :
- I executed run.bat in order to have auto-gpt running
- I ingested some files via data_ingestion.bat ( the file ingested are some .pdf and .txt files)
- I observed the dimension of AutoGpt.json increased up to 2MB
- When I asked other tasks to auto-gpt, the dimension of AutoGpt.json come back to 1 KB, it seems he loosed the data ingested

### Current behavior 😯

Dimension of AutoGpt.json come back to 1K after data ingested, when are asked to auto-gpt other tasks after ingestions

### Expected behavior 🤔

I expected that after ingestion the dimension of AutoGpt.json files continued to increase after the ingestion of files.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Slowly-Grokking** [comment] 2023-04-19 00:29
I've been playing around with redis memory retrieval a bit today, and i believe this is most likely because "get_memory(cfg, init=True)" or similar is being called.  I'm just starting to make sense of autogpt's flow, but it appears that memory is getting initialized multiple times. 

if someone wants to look into this I'd check for instances where memory(cfg) is called where "get_memory(cfg, init=False), could be used, as well as making sure that the def of get_memory is not hardcoded to true.

**Comment by Pwuts** [comment] 2023-04-29 15:06
Duplicate of #623, please add to that issue

**Closed by Pwuts** 2023-04-29 15:06 UTC
Labels: needs investigation, function: memory
