### ISSUE TITLE
Error:  API Rate Limit Reached. Waiting 10 seconds...

### ISSUE THREAD

**Issue by bbriggs1990** [Significant-Gravitas/Auto-GPT#425] opened 2023-04-07 21:11 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/119343793/230679513-7251c11a-0666-42ca-bad0-486f930c196d.png)

### Current behavior 😯

Doesn't run

### Expected behavior 🤔

Runs

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by CanyonTurtle** [comment] 2023-04-07 21:53
I have the same issue, using gpt3.5 on windows w/ python 3.10.6 and pinecone free tier with default project.

**Comment by CanyonTurtle** [comment] 2023-04-07 22:05
![Screenshot 2023-04-07 160314](https://user-images.githubusercontent.com/12898440/230684655-05e3bac5-fe44-456b-8e76-86740ed4a03b.png)

By printing the exception details, it looks like I simply don't have any API calls (I'm not paying for the API or anything).

**Comment by CanyonTurtle** [comment] 2023-04-07 22:10
Suggestion to author @Torantulino: 
1. perhaps a little blurb in the requirements section that explains that you need to have API credits in order to use this, and/or
2. Changing this exception message to something like "API Rate Limit Reached (do you have enough API credits to use the openai API?) Waiting..."

**Comment by dudiyalov** [comment] 2023-04-08 06:16
Same here:
Using memory of type: PineconeMemory
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...

**Comment by shubhamgoyal42** [comment] 2023-04-08 06:29
Same

```
Using memory of type: PineconeMemory
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
/ Thinking...
```

**Comment by Hiltso** [comment] 2023-04-08 09:02
Same here. I am using the Pinecone starter account. Looks like it doesnt like the Pincone Starter account API details. 
Using memory of type: PineconeMemory
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
/ Thinking...

Until I figure this out, I would like to remove Pinecone. I have deleted the ENV variables  for Pincone and edited the .env file to remove those likes but it keeps coming back to this error.

Also I presume this is a typo in Pincone section for Windows users to set up ENV vars? setx instead of export?
For Windows Users:

setx PINECONE_API_KEY "YOUR_PINECONE_API_KEY"
export PINECONE_ENV="Your pinecone region" # something like: us-east4-gcp

**Comment by AlexTs10** [comment] 2023-04-08 09:56
i have the same problem. Using paid openai api and pinecone free trial. Openai api works when i directly use it and with langchain.

**Comment by dudiyalov** [comment] 2023-04-08 10:01
- I had deleted the index in Pinecone and created a new one.
-  I had set a paid account on open.ai and set billing limits.
Now it works just fine.

**Comment by shubhamgoyal42** [comment] 2023-04-08 10:25
Me too, I created a paid account in openAI an now it works fine

**Comment by AlexTs10** [comment] 2023-04-08 10:58
found the problem.
On windows the openai_api_key is not set properly even if i write it at the .env file.
-- When i installed in a new conda env it used a default key.
I had to set it manually and then worked properlly.

**Comment by Hiltso** [comment] 2023-04-08 11:24
Works After I added a few $ to my openai account.  

It was bombing with Pincone errors which was throwing me off.

I noticed in Openai Usage tab on the right hand column was at $0.00 / $0.00 meaning no tokens available. Now after adding a couple of dollars it works.
I also set Usage Limit in the Billing menu to 3$ for now (rather than the default 120$ :)

**Comment by JuroOravec** [comment] 2023-04-14 11:33
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @bbriggs1990 would you close this one issue if it indeed is the same thing?

(I had this issue too - It's that we haven't [opted into "paid account" on OpenAI's billing page](https://platform.openai.com/account/billing/overview))

I'm making an MR as we speak to update the README section on OpenAI's API key, to make this clear.

**Closed** 2023-04-16 12:59 UTC
