### ISSUE TITLE
Exceeding max tokens (4097) limit 

### ISSUE THREAD

**Issue by Sean19899999** [Significant-Gravitas/Auto-GPT#1211] opened 2023-04-14 00:17 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

TeacherGPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
TeacherGPT is: an AI designed to autonomously generate teaching powerpoint slides based on the teaching issue provided.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Generate slides related to the issue "abalone heterosis"
Goal 2: Ultilize the cut-edge science frontiers
Goal 3: Generate markdown format texts
Goal 4: The slides should be well organized and structured
Goal 5:
Using memory of type: PineconeMemory
TEACHERGPT THOUGHTS:  I think it would be best to start by researching what abalone heterosis is and what the current scientific thinking is around it.
REASONING:  To be able to generate powerpoint slides related to abalone heterosis and utilize cutting edge research, I need to research the issue so I can provide accurate and valuable information. This will require the use of a Google Search command.
PLAN:
-  Use the 'google' command to search for information about abalone heterosis
-  Skim through the relevant information to understand the key concepts and information around abalone heterosis
-  Take key notes about the concepts and information
CRITICISM:  I need to make sure that I am efficient with my search to reduce the time that the search command takes so that I can start work on creating the slides in a reasonable amount of time.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'abalone heterosis'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for TeacherGPT...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command google returned: ['https://pubmed.ncbi.nlm.nih.gov/34496767/', 'https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-021-07954-y', 'https://www.sciencedirect.com/science/article/abs/pii/S0044848622003477', 'https://www.nature.com/articles/hdy2014124', 'https://www.sciencedirect.com/science/article/pii/S0044848622003477', 'https://www.frontiersin.org/articles/10.3389/fmars.2021.667636/full', 'https://onlinelibrary.wiley.com/doi/pdf/10.1111/are.15779',
 'https://www.frontiersin.org/articles/10.3389/fmars.2022.1013447/full']
TEACHERGPT THOUGHTS:  Now that I have some information related to abalone heterosis, I will browse some selected website(s) to acquire a better understanding of the current scientific thinking and research around blue mussel aquaculture.
REASONING:  I have several sources of information from the google search results which contains useful information that can be utilized for the creation of the teaching slides. I need to browse the relevant websites to gain a deep understanding of the scientific research and thinking around the subject to create valuable slides
PLAN:
-  Browse through the selected webpages provided by the Google search command to get a better understanding of the current research and scientific thinking around abalone heterosis
-  Take detailed notes about the keywords, phrases, and concepts related to abalone heterosis that will be highlighted on the teaching slides
CRITICISM:  I need to make sure that the browsing process does not take too much of my allocated memory and I do not get
 distracted by irrelevant information.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.nature.com/articles/hdy2014124', 'question': 'What is the current thinking around abalone heterosis?'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for TeacherGPT...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
Text length: 60573 characters
Summarizing chunk 1 / 4
Summarizing chunk 2 / 4
**SYSTEM:  Command browse_website returned: Error: This model's maximum context length is 4097 tokens. However, your messages resulted in 9861 tokens. Please reduce the length of the messages.**

### Current behavior 😯

Using chatGPT 3.5 API，generating the following issue:

> SYSTEM:  Command browse_website returned: Error: This model's maximum context length is 4097 tokens. However, your messages resulted in 9861 tokens. Please reduce the length of the messages.

### Expected behavior 🤔

Program continue.

### Your prompt 📝

```yaml
AI Name: TeacherGPT
TeacherGPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
TeacherGPT is: an AI designed to autonomously generate teaching powerpoint slides based on the teaching issue provided.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Generate slides related to the issue "abalone heterosis"
Goal 2: Ultilize the cut-edge science frontiers
Goal 3: Generate markdown format texts
Goal 4: The slides should be well organized and structured
Goal 5:
```

**Comment by courtsimas** [comment] 2023-04-14 03:03
are you using the gpt 3.5 model or 4?

**Comment by SlistInc** [comment] 2023-04-14 09:38
This seems related to / a duplicate of #796

**Comment by Sean19899999** [comment] 2023-04-15 12:31
> are you using the gpt 3.5 model or 4?

3.5

**Comment by kobentori** [comment] 2023-04-16 07:00
I was using the GPT-4 model and have come upon this issue three or so times. AutoGPT will use the /read file/ command to read its entire directory - and understanding that the bot has certainly created a lot of files and code abstracts, the program will end because of the token request error.

**Comment by SlistInc** [comment] 2023-04-16 07:02
I am using GPT-3.5 and run into this issue as well as soon as Auto-GPT wants to scan / list the content of a folder of more than 500 or so files. So it should be a reproducable issue.

**Comment by Pwuts** [comment] 2023-04-18 00:07
Closing as duplicate of #38, #796

**Closed by Pwuts** 2023-04-18 00:07 UTC

**Comment by Vaibhavcste** [comment] 2023-05-11 02:37
Did you guys find a workaround for this, my agent is always stopping due to this?

**Comment by vjzamo** [comment] 2023-05-17 11:20
I think it's easier than it seems, you can skip this error and teach it to look for a solution, here is the response given by the agent, indicating that the query would exceed the maximum number of tokens and reduce their use

Example:
**Input:** Please note the following error and reduce token usage and continue with the project. openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 10200 tokens. Please reduce the length of the messages

**SYSTEM**: message_agent command returned: Error: The maximum context length of this model is 4097 tokens. However, his messages generated 4,367 tokens. Please reduce the length of messages.

And continue processing

**Comment by spandera-graphics** [comment] 2023-06-13 12:14
# FAST_TOKEN_LIMIT=4000
# SMART_TOKEN_LIMIT=4000
change to this in .env and it will be solved . this works only if you use gpt 3

**Comment by Pwuts** [comment] 2023-06-13 16:00
Token limit enforcement should be more reliable since #4498, so your suggestion won't have any effect in `master` or starting with the next release 0.4.1 @spandera-graphics.
