### ISSUE TITLE
generate_image_with_dalle() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by amainiero** [Significant-Gravitas/Auto-GPT#2507] opened 2023-04-19 07:22 UTC
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Have a prompt that results in the assistant trying to generate an image

### Current behavior 😯

SYSTEM:  Command generate_image returned: Error: generate_image_with_dalle() takes 2 positional arguments but 3 were given

### Expected behavior 🤔

Assistant successfully generates an image using dalle by providing the correct number of arguments.

### Your Logs 📒

THOUGHTS:  I will use the 'generate_image' command to create an image of a savings plan that can be used in the course materials. I will also use the 'write_to_file' command to save the image to a file that can be used in the course materials.
REASONING:  Creating an image of a savings plan will help learners to visualize the concept and understand how to save money. Saving the image to a file will allow it to be easily used in the course materials.
PLAN:
-  Use the 'generate_image' command to create an image of a savings plan
-  Use the 'write_to_file' command to save the image to a file that can be used in the course materials
CRITICISM:  I need to make sure that the image is clear and easy to understand. I should also consider the file format of the image to make sure that it can be easily used in the course materials.
NEXT ACTION:  COMMAND = generate_image ARGUMENTS = {'prompt': 'Create an image of a savings plan with different categories of savings, such as emergency fund, retirement, and short-term goals. Label each category with a percentage or dollar amount to show how much of the savings plan is allocated to each category.', 'model': 'image-alpha-001', 'save_path': 'savings_plan.png'}
SYSTEM:  Command generate_image returned: Error: generate_image_with_dalle() takes 2 positional arguments but 3 were given

**Comment by shashankboosi** [comment] 2023-04-19 07:25
I think there are PRs open for this fix https://github.com/Significant-Gravitas/Auto-GPT/pull/2491, https://github.com/Significant-Gravitas/Auto-GPT/pull/2501
So should be resolved soon, till then you can use the stable branch. Thanks :)

**Comment by amainiero** [comment] 2023-04-19 09:49
New to posting on github so maybe I selected the wrong branch when creating the issue. This occurred on the stable branch,

**Comment by shashankboosi** [comment] 2023-04-19 23:21
I checked on the stable branch and looks like it is on there as well. Just have to wait for the fix to be merged. Till then, you can use the code changes from the PR and change it locally to get your assistant working. Thanks

**Comment by namba06530** [comment] 2023-04-20 13:24
Just add "size" on image_gen.py
def generate_image_with_dalle(prompt: str, filename: str, size) -> str:

**Comment by kinance** [comment] 2023-04-20 15:17
Duplicate of  #2645

**Comment by ntindle** [comment] 2023-04-21 03:59
Duplicate of #2645

**Closed by ntindle** 2023-04-21 03:59 UTC

**Comment by froggomad** [comment] 2023-04-22 03:40
> Just add "size" on image_gen.py def generate_image_with_dalle(prompt: str, filename: str, size) -> str:

I also had to add `filename: str` to `generate_image`... I'm on stable
