### ISSUE TITLE
NEXT ACTION:  COMMAND = Error: ARGUMENTS = string indices must be integers

### ISSUE THREAD

**Issue by petersevera** [Significant-Gravitas/Auto-GPT#1285] opened 2023-04-14 09:24 UTC
### Duplicates

- [X] I have searched the existing issues

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment] 2023-04-18 04:28
Closing as duplicate of #389

**Closed by Pwuts** 2023-04-18 04:28 UTC
