### ISSUE TITLE
y -Y option

### ISSUE THREAD

**Issue by sujitrp** [Significant-Gravitas/Auto-GPT#2147] opened 2023-04-17 10:14 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Same Way y -Y option 
 I know --continuous will do the same. But the middle of execution no option make it  continuous 

### Examples 🌈

Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Same Way y -Y option 
 I know --continuous will do the same. But the middle of execution no option make it  continuous 

### Motivation 🔦

Various try on CgatGPT 3 turbo

**Comment by ntindle** [comment] 2023-04-20 08:13
duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/150, https://github.com/Significant-Gravitas/Auto-GPT/issues/1472

**Closed** 2023-04-21 04:44 UTC
Labels: enhancement
