### ISSUE TITLE
Open source models support

### ISSUE THREAD

**Issue by ArsenKakasyan** [Significant-Gravitas/Auto-GPT#143] opened 2023-04-04 03:53 UTC
Any thoughts on adding support for custom open source models like LLaMa, Alpaca, Alpaca-lora, etc?

**Comment by MarkSchmidty** [comment] 2023-04-04 16:25
There's a closed PR from two days ago that added local model support. https://github.com/Torantulino/Auto-GPT/pull/29

Not sure what the status is right now. But I don't see anywhere in the current code capable of sending requests anywhere other than the OpenAI API, which is disappointing.

-------

>Alpaca, Alpaca-lora, etc

On a bit of a tangent, the recently released Vicuna is far superior to Alpaca and other fine tunes. While Alpaca is trained on 60k synthetic question/answer pairs by GPT-3.5 and GPT4All is trained on 400k GPT-3.5 synthetic question/answers, Vicuna is trained on 90k full conversations (multiple question/answers each) between real humans and GPT-4 or GPT-3.5. The dataset for this comes from ShareGPT and can be accessed here: https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/tree/main/HTML_cleaned_raw_dataset

**Comment by MarkSchmidty** [comment] 2023-04-04 16:28
This issue might be a duplicate of https://github.com/Torantulino/Auto-GPT/issues/25

**Comment by 9cento** [comment] 2023-04-09 09:40
+1

**Comment by Kenshiro-28** [comment] 2023-04-10 10:41
+1

**Comment by Pwuts** [comment] 2023-04-18 00:39
Closing as duplicate of #25

**Closed by Pwuts** 2023-04-18 00:39 UTC
