### ISSUE TITLE
Please fix the chunking issue, which makes browse_website unusable

### ISSUE THREAD

**Issue by Nickonomic** [Significant-Gravitas/Auto-GPT#1820] opened 2023-04-16 08:37 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

It is trying to process 20 chunks worth 89669 tokens:

Adding chunk 17 / 20 to memory
SYSTEM:  Command browse_website returned: Error: This model's maximum context length is 8191 tokens, however you requested 89669 tokens (89669 in your prompt;
 0 for the completion). Please reduce your prompt; or completion length.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment] 2023-04-18 00:07
Closing as duplicate of #38, #796

**Closed by Pwuts** 2023-04-18 00:07 UTC
