### ISSUE TITLE
Error When Trying to Run for First time

### ISSUE THREAD

**Issue by ronrevog** [Significant-Gravitas/Auto-GPT#1669] opened 2023-04-15 18:31 UTC
pymilvus not installed. Skipping import.
Warning: The file 'auto-gpt.json' does not exist.Local memory would not be saved to a file.

ive done a search in issues but cant seem to find answer any idea?

thanks!

**Comment by Nickonomic** [comment] 2023-04-15 18:34
> pymilvus not installed. Skipping import. Warning: The file 'auto-gpt.json' does not exist.Local memory would not be saved to a file.
> 
> ive done a search in issues but cant seem to find answer any idea?
> 
> thanks!

You can manually create a file auto-gpt.json, open it with notepad, put '{}' in it, and run again. Will fix the local memory issue.

**Comment by pswami** [comment] 2023-04-15 18:37
Also be sure to be in the `stable` branch

**Comment by ronrevog** [comment] 2023-04-15 19:01
the json file fixed the Warning error, but this error is still there:

pymilvus not installed. Skipping import.

am i inputting the open ai api incorrectly? im just copying and pasting into the .env file in right spot i think.

**Comment by guppyO** [comment] 2023-04-15 20:59
Where exactly should I put the auto-gpt.json file and do I make it a PY file as txt? 

Thanks.

**Comment by Pegasust** [comment] 2023-04-15 21:03
Just a simple `{}` should suffice

**Comment by guppyO** [comment] 2023-04-15 21:17
yes this has fixed the error. thanks

**Comment by PopkenDev** [comment] 2023-04-15 21:55
Where exactly do you need to put the json file?

**Comment by guppyO** [comment] 2023-04-16 01:38
Inside the auto-gpt folder

**Comment by nurhakam** [comment] 2023-04-16 04:45
Error when running for the first time `v0.2.0`, missing some requirements module.

```
> python -m autogpt
pymilvus not installed. Skipping import.
Warning: The file 'auto-gpt.json' does not exist.Local memory would not be saved to a file.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\Auto-GPT\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "...\Auto-GPT\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "...\Auto-GPT\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "...\Auto-GPT\autogpt\app.py", line 27, in <module>
    from autogpt.commands.twitter import send_tweet
  File "...\Auto-GPT\autogpt\commands\twitter.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
```

Fix 
1. Create a `auto-gpt.json` file in the main Auto-GPT folder and add `{}` to the file.
2. Install the missing module.
- `pip install pymilvus`
- `pip install tweepy`
3. Run `python -m autogpt` again.

**Comment by Pwuts** [comment] 2023-04-19 15:51
Closing as duplicate of #1073

**Closed by Pwuts** 2023-04-19 15:51 UTC
