### ISSUE TITLE
Modular Abilities

### ISSUE THREAD

**Issue by henryruss3** [Significant-Gravitas/Auto-GPT#953] opened 2023-04-12 13:23 UTC
### Duplicates

- [x] I have searched the existing issues

### Summary 💡

There is a folder called "abilities" under scripts that has modular folders for abilities the AI can perform. Inside the folder are python files that can do anything. The AI can call it by outputting "run [FILE_NAME]".

### Examples 🌈

I make an ability for the AI to tweet using the Twitter API.
I tell it to get as many followers on Twitter as possible. 
It can actually post things on twitter because of this.

### Motivation 🔦

AGI

**Comment by Pwuts** [comment] 2023-04-18 03:45
I think this is a duplicate of #757

**Closed by Pwuts** 2023-04-18 03:45 UTC
