### ISSUE TITLE
Title: Repeated "Error: API Rate Limit Reached" messages when running the script  Issue:  I have tried running Auto-GPT from the master branch. Commit-hash: a0f900f2dabd114f80d5e96ecc6269a744dfc99a Pip version: pip 23.0.1 Python version: 3.11.3 The issue occurs when running the script using the following command: python scripts/main.py

### ISSUE THREAD

**Issue by ibaleve** [Significant-Gravitas/Auto-GPT#1047] opened 2023-04-13 04:16 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Clone the Auto-GPT repository.
Install the required dependencies.
Run the script using the command: python scripts/main.py

### Current behavior 😯

The script repeatedly shows "Error: API Rate Limit Reached. Waiting 10 seconds..." messages and does not seem to progress.

### Expected behavior 🤔

The script should run without encountering API rate limit errors, or it should handle the rate limits gracefully and continue running after waiting.

### Your prompt 📝

# No specific prompt was used

**Comment by skynet01** [comment] 2023-04-13 05:43
This happens if you are on a free account with OpenAI, you have to add your billing info and it will start working. I wish this was documented in the readme, I think all of us went through this.

**Comment by ibaleve** [comment] 2023-04-13 06:10
I'm not on the a free account I have ChapGPT Plus

**Comment by ibaleve** [comment] 2023-04-13 06:22
I understand what you saying now @skynet01 I had to do some research. Thanks

**Comment by dablurr** [comment] 2023-04-13 15:45
Upgraded on a GPT4 plan, went ahead and re generated my keys. Added my key but I am still running upon the same issue. am I missing some steps or something ?

**Comment by noammo-max** [comment] 2023-04-13 18:15
same here @ibaleve  can you share what solved the issue for you?

**Comment by JuroOravec** [comment] 2023-04-14 11:24
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @ibaleve would you close this one issue if it indeed is the same thing?

(I had this issue too - It's that we haven't [opted into "paid account" on OpenAI's billing page](https://platform.openai.com/account/billing/overview). The `auto-gpt.json` is a red herring - it's a last messag we see, but it's unrelated to the API limit reached, the script can work without the auto-gpt.json)

I'm making an MR as we speak to update the README section on OpenAI's API key, to make this clear.

**Comment by Qoyyuum** [comment] 2023-04-16 15:38
1. upgrade to a paid account: https://platform.openai.com/account/billing/overview
2. ChatGPT+ != paid account. 
3. add a payment method: https://platform.openai.com/account/billing/payment-methods (optional) set my usage limits: https://platform.openai.com/account/billing/limits
4. create a new API key: https://platform.openai.com/account/api-keys (old API key did not work, i guess it was not update with my payment information automatically)
5. replace the value for the autogpt/.env files's OPENAI_API_KEY.

Closing issue.

**Closed by Qoyyuum** 2023-04-16 15:38 UTC
