### ISSUE TITLE
0.3.0 master testing no matter what length prompt, I get the following: openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 73070 tokens (73070 in your prompt; 0 for the completion). Please reduce your prompt; or completion length."

### ISSUE THREAD

**Issue by caressgents** [Significant-Gravitas/Auto-GPT#3362] opened 2023-04-26 22:51 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Run this prompt or something similar that will make autogpt git clone a repo:

Prompt: "do a full audit and test my application in this repo https://github.com/Significant-Gravitas/Auto-GPT.git then save your outputs to .txt file"

### Current behavior 😯

It will analyze and create it's plan, prompts, etc - but when it gets to first step trying to clone the repo, it hangs for a bit and spits out this error:

openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 73070 tokens (73070 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.

It's requesting way too many tokens at this point of trying to clone a repo. 

I tested running a prompt without a git, just a research based prompt, and it's running normally.

### Expected behavior 🤔

expected behavior is to clone the git repo to workspace, audit files, chunk out data store to memory, etc. etc.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by NKT00** [comment] 2023-04-26 23:41
I think this is user error though? You're asking the AI to download the repo into memory and interpret it, and the result is just too big for the number of tokens available to the AI.

However, it is an issue that pops up with a lot of the web searches AutoGPT tries to run.

**Comment by caressgents** [comment] 2023-04-26 23:45
> I think this is "user error"* though? You're asking the AI to download the repo into memory and interpret it, and the result is just too big for the number of tokens available to the AI.
> 
> 
> 
> *Not really the user as in you, the AI is trying to go beyond the limitations we have set. However, it is an issue that pops up with a lot of the web searches AutoGPT tries to run.

Yeah, getting it a lot on searches. I thought it was chunking and condensing and I may be dreaming, but I thought on stable I was running repo audits this same way, I just tested again and got the same errors. Maybe it was just scraping the code before rather than cloning though.. wish I logged it better, in retrospect

**Comment by NKT00** [comment] 2023-04-26 23:59
Oh, it is defo an issue! I've just added a suggestion that it switch models automatically when it knows ahead of time that the token count exceeds whatever model it is going to try.

**Comment by osengaa10** [comment] 2023-04-27 00:07
I get this error even when it's running an 'execute_shell' command: 
`Executing command 'cd ~ && wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.12.0/ncbi-blast-2.12.0+-x64-linux.tar.gz && tar -zxvf ncbi-blast-2.12.0+-x64-linux.tar.gz && rm ncbi-blast-2.12.0+-x64-linux.tar.gz && export PATH=$PATH:$PWD/ncbi-blast-2.12.0+/bin' in working directory '/home/austin/notebook/ai/Auto-GPT/auto_gpt_workspace'`

I does the execute_shell command call the openAPI? I thought it'd just be running the above command on my local.

**Comment by Pwuts** [comment] 2023-04-27 12:58
@osengaa10 the output of the command is returned to the GPT so it can examine the outcome. What kind of output does the command give?

**Comment by Pwuts** [comment] 2023-04-27 14:29
Thanks for providing the log. This is a duplicate of #3244 and will be fixed by #3222

**Closed by Pwuts** 2023-04-27 14:29 UTC
