### ISSUE TITLE
This fixed it for me, as you're using docker-compose I assume, update your `docker-compose.yml` file to:

### ISSUE THREAD

**Issue by cryptskii** [Significant-Gravitas/Auto-GPT#4034] opened 2023-05-08 21:19 UTC
This fixed it for me, as you're using docker-compose I assume, update your `docker-compose.yml` file to:

```
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    profiles: ["exclude-from-up"]
    volumes:
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data
      ## allow auto-gpt to write logs to disk
      - ./logs:/app/logs
      ## uncomment following lines if you have / want to make use of these files
      #- ./azure.yaml:/app/azure.yaml
      #- ./ai_settings.yaml:/app/ai_settings.yaml
  redis:
    image: "redis/redis-stack-server:latest"
```

_Originally posted by @mousberg in https://github.com/Significant-Gravitas/Auto-GPT/issues/4029#issuecomment-1538952921_

**Comment by cryptskii** [comment] 2023-05-08 21:20
what in this is different than default?

**Comment by delconis** [comment] 2023-05-09 00:21
I recently pulled the project and the `./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace` path was not correct, this shows the correct path for the auto_gpt_workspace is what I see

**Comment by delconis** [comment] 2023-05-09 00:25
related #4029

**Comment by anonhostpi** [comment] 2023-05-09 01:40
If you want to ask clarifying questions on another issue, don't make a duplicate, just ask on the other thread. This will likely get closed.

Duplicate of #4029

**Comment by suparious** [comment] 2023-05-10 20:26
the format for docker storage mappings is `<local_mount_point>:<docker_mount_point>`

So the user can configure any folder they want for `<local_mount_point>` and suggesting that should be `./auto_gpt_workspace` seems very opinionated.

**Comment by k-boikov** [comment] 2023-05-10 21:21
Fixed with https://github.com/Significant-Gravitas/Auto-GPT/pull/3927

**Closed by k-boikov** 2023-05-10 21:21 UTC
