### ISSUE TITLE
API Rate Limit issue

### ISSUE THREAD

**Issue by RichGapple** [Significant-Gravitas/Auto-GPT#585] opened 2023-04-09 11:55 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...

This is the only error im getting and I have run python scripts/main.py --gpt3only

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by tuapuikia** [comment] 2023-04-09 13:42
Open API chatgpt is not a free service. You can resolve this by adding credit card to your openai account.

**Comment by AramisValdes** [comment] 2023-04-09 15:47
Having the same issue, i have premium GPT account.

**Comment by Slamsneider** [comment] 2023-04-09 16:57
"premium GPT account" is not enough. You need to go here: https://platform.openai.com/account/billing/overview and make a $ account for tokens.

Then you can also use the ($) playground. https://platform.openai.com/playground

Remember to set a soft and hard limit or you can loose control of your money spending.

**Comment by disneytoy** [comment] 2023-04-09 18:33
Same issue. I just paid for GPT Plus $20 a month. So that isn't enough to use the API?

**Comment by tuapuikia** [comment] 2023-04-09 19:22
Chatgpt plus is for web chat, API have different billing.

**Comment by marcocastignoli** [comment] 2023-04-10 06:15
I know some libraries use the web token to interact with chatgpt instead of using OpenAI API token. Are there mandatory features in the api that prevent you allowing users to verify themself through the web token?

If not, I'd be available to integrate the web token.

**Comment by tuapuikia** [comment] 2023-04-10 07:05
> I know some libraries use the web token to interact with chatgpt instead of using OpenAI API token. Are there mandatory features in the api that prevent you allowing users to verify themself through the web token?
> 
> If not, I'd be available to integrate the web token.

"Is it possible to specify GPT4 model when using the web token method?

**Comment by marcocastignoli** [comment] 2023-04-11 06:58
I just checked a request to the web api.


{"action":"next","messages":[{"id":"6bee6a9c-8211-4597-a602-b695a2787615","author":{"role":"user"},"content":{"content_type":"text","parts":["hello"]}}],"parent_message_id":"9fde1d70-23d7-4e21-9826-5d67ae88f397",**"model":"gpt-4"**,"timezone_offset_min":-120}

Seems like you can specify the model.

**Comment by JuroOravec** [comment] 2023-04-14 11:32
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @patrickelectric would you close this one issue if it indeed is the same thing?

(I had this issue too - It's that we haven't [opted into "paid account" on OpenAI's billing page](https://platform.openai.com/account/billing/overview))

I'm making an MR as we speak to update the README section on OpenAI's API key, to make this clear.

**Closed** 2023-04-16 15:21 UTC
