### ISSUE TITLE
Any plan to support chatglm models？

### ISSUE THREAD

**Issue by wxbty** [Significant-Gravitas/Auto-GPT#945] opened 2023-04-12 11:37 UTC
### Duplicates

- [X] I have searched the existing issues

**Comment by james431987** [comment] 2023-04-13 13:52
https://www.youtube.com/watch?v=fGpXj4bl5LI

I can't imagine autoGPT not allowing for the ability to use a model that can run on consumer-grade electronics.
Cool to know that chatglm is the best one for the job right now.

maybe OpenAI can implement a GPT-light version.

**Comment by Pwuts** [comment] 2023-04-18 04:42
Closing as duplicate of #25, please add to that issue! :)

**Closed by Pwuts** 2023-04-18 04:42 UTC
Labels: question

**Comment by sunshinecf** [comment] 2023-06-27 03:21
Want to access chatGlm,You solved it
