### ISSUE TITLE
Failed to parse AI output, attempting to fix.  If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.

### ISSUE THREAD

**Issue by yunga1** [Significant-Gravitas/Auto-GPT#319] opened 2023-04-06 14:16 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Upgraded to latest version with Pinecone. Prompts that worked great yesterday now break constantly. Throwing the error:

Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
 
 I'm using GPT3.5.

### Your prompt 📝

designAI

An AI created to help with design direction for a SaaS company

Research 2023 graphic design trends

Take 10 of the trends, and list them with description in a csv file

**Comment by notflip** [comment] 2023-04-06 15:36
Same here! It occurs after 10 or 20 runs and doesn't go away afterwards

**Comment by yunga1** [comment] 2023-04-06 17:05
Can anyone with GPT4 access confirm the prompt works for 4 but not 3.5?

**Comment by mazurkind** [comment] 2023-04-06 17:48
Same here, gpt3only, and same error after approx 1min.

**Comment by heikog** [comment] 2023-04-06 19:36
got the same error on gpt-4. . didn't find a way to fix it

**Comment by michaljerzylew** [comment] 2023-04-06 20:39
Confirmed with GPT4

Command list returned: Unknown command list
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
Error: Invalid JSON

**Comment by KingRekter** [comment] 2023-04-06 20:45
it misses a closing curly bracket at the end of the json

**Comment by Torantulino** [comment] 2023-04-06 21:59
@KingRekter Good spot!
Which script are you referring to?

Let's get this fixed!

**Comment by jantic** [comment] 2023-04-06 22:36
I seem to be getting much better json generation behavior after I change this in prompt.txt:

From this:

`You should only respond in JSON format as described below.`

`You should only respond in JSON format as described below. Note that all of these fields are mandatory in the schema.`

I'm wondering if others see the same results....

**Comment by jantic** [comment] 2023-04-06 22:38
I do also have this in there but it didn't seem to make a difference:

> Review your own json output, step by step.

**Comment by jdrusso** [comment] 2023-04-06 23:11
> I seem to be getting much better json generation behavior after I change this in prompt.txt:
> 
> From this:
> 
> > You should only respond in JSON format as described below.
> 
> To this:
> 
> > You should only respond in JSON format as described below. Note that all of these fields are mandatory in the schema.
> 
> I'm wondering if others see the same results....

Yep, this has majorly improved the consistency of my replies. I was getting the failures before extremely frequently, I haven't seen any so far since including this.

**Comment by jantic** [comment] 2023-04-07 00:10
> Yep, this has majorly improved the consistency of my replies. I was getting the failures before extremely frequently, I haven't seen any so far since including this.

I helps and so I think it points in a right direction. But I'm still getting weird issues like the model just disregarding json output altogether and just responding in plain text. I'm going to keep trying ways to coax it into doing the right thing but it seems pretty stubborn- at least with GPT-3.5. My guess is it's much more reliable with GPT4 but I can't verify myself...

**Comment by jdrusso** [comment] 2023-04-07 01:40
Anecdotally, I have had better luck with GPT4 so far. One thing that may help you is telling it "Please be sure to format your reply in the correct JSON schema", which gets it back on track for a bit.

**Comment by nithronium** [comment] 2023-04-07 02:10
The problem sometimes happens when the expected return data is a JSON and the bot tries to re-fetch that. For example if I ask for it to JSON decode some data, it sometimes decodes correctly and writes output to a file and sometimes messes up and I see the data in the command prompt on "reasoning" or other places. 

Perhaps parsing the response to check if JSON is there, if yes, check if it's valid, if yes -> proceed, if any one of those fails, re-ask the question to the AI or show the prompt file without breaking the script. The problem is not with the returned JSON response being wrong, the issue is that broken JSON breaks the commands as well.

**Comment by jadeowaowa** [comment] 2023-04-07 04:59
same issue here on GPT4, even after changing:
"Please be sure to format your reply in the correct JSON schema" to "You should only respond in JSON format as described below. Note that all of these fields are mandatory in the schema."
and also telling it to reply in the correct JSON schema via feedback.

**Comment by theholymath** [comment] 2023-04-07 05:31
Getting the same error with GPT-4. Tried a number of fixes in `prompt.txt` with no luck.

**Comment by ChessScholar** [comment] 2023-04-07 06:04
Putting "Critical:" in front of  "You should only respond in JSON format as described below. Note that all of these fields are mandatory in the schema." fixed the json issue for me, but it keeps mentioning "Warning: Failed to parse AI output, attempting to fix." without the json error.


And put this at the end:

> Make sure to format your reply in the correct JSON schema.
> Ensure the response can be parsed by Python json.loads


Group effort!

**Comment by MicrowaveJak** [comment] 2023-04-07 07:25
I have had a lot of success with explicitly telling it to only respond in valid JSON, with no additional instructions. Not token efficient but it's been working consistently for me so far.

`{...}

PERFORMANCE EVALUATION:

1. Review and analyze your actions to ensure you are performing to the best of your abilities. 
2. Constructively self-criticize your big-picture behavior constantly.
3. Reflect on past decisions and strategies to refine your approach.
4. Every command has a cost, so be smart and efficient. Aim to complete tasks in the least number of steps.

CRITICAL! You may only respond in JSON format as described below. Go carefully and step by step. 
Do not output any additional instructions outside of the JSON format. Under no circumstances should your response deviate from valid JSON format.

RESPONSE FORMAT:
{
    "thoughts":
    {
        "text": "thought",
        "reasoning": "reasoning",
        "plan": "- short bulleted\n- list that conveys\n- long-term plan",
        "criticism": "constructive self-criticism",
        "speak": "thoughts summary to say to user"
    },
    "command": {
        "name": "command name",
        "args":{
            "arg name": "value"
        }
    }
}

Be absolutely sure the response can be parsed by Python json.loads.  
`

**Comment by yunga1** [comment] 2023-04-07 16:04
I still get this behavior on the newest Pinecount build. Regardless of what I try. Using the older build I do get great results, with the same prompts. Not sure if it's related to Pinecone, or something else that got merged.

**Comment by ChessScholar** [comment] 2023-04-07 16:10
Posting around a fix:

Auto-GPT > scripts > json_parser:
[json_parser.txt](https://github.com/Torantulino/Auto-GPT/files/11180068/json_parser.txt)

Auto-GPT > scripts > data
[prompt.txt](https://github.com/Torantulino/Auto-GPT/files/11180069/prompt.txt)


Thanks for the ideas guys! 
https://github.com/Torantulino/Auto-GPT/discussions/401

**Comment by SunilWarrier** [comment] 2023-04-07 19:02
Not that helpful yet for me.

Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
NEXT ACTION:  COMMAND = Error: ARGUMENTS = Missing 'command' object in JSON
SYSTEM:  Command Error: returned: Unknown command Error:
Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix ai output, telling the AI.
Error: Invalid JSON

The problem persists even after today’s update, I am using GPT 3.5. I’ve encountered this issue repeatedly with no improvement even after 20-30 attempts. It has been consistent throughout before, and even when I left it running overnight, the same problem persisted. Eventually, it got hung with the same error after a prolonged period of time.

**Comment by ChessScholar** [comment] 2023-04-07 19:22
I'm noticing the same issue with COMMAND = ARGUMENTS = {}

I did a quick fix, but it seems there are more files to edit to make the coding congruent.

**Comment by dahifi** [comment] 2023-04-08 14:52
I used the following to escape the erroneous state: 
`Input:I think your prompt is bugged. Youve lost the ability to run commands. I need to run a quick test to make sure you can use the correct RESPONSE FORMAT. Use the write_to_file command to create /Users/bcm/Auto-GPT/text.txt`

I think we should allow the model to prompt us for clarifying info. I had to reduce the prompt to 2000 words and told it to accept user input. 

I think it's a good case to allow the model to talk back an ask questions, not everything needs to a command to another agent, as I'm not even sure what I want it to do quite yet.

**Comment by jantic** [comment] 2023-04-08 16:19
>  I had to reduce the prompt to 2000 words and told it to accept user input.

I've been wondering if the core problem is simply asking the model to do too much at once. Perhaps the different functionalities (task planning, criticism, execution, etc) need to be broken up into separate calls (or agents). And I'd go even further to suggest that perhaps forcing replies to be in json is asking to much and makes the functionality fragile. I see BabyAGI as a good reference for an alternative approach like this.

Of course this is a significant change but I think this is where the evidence is leading...

**Comment by lupuleasa-core** [comment] 2023-04-09 00:21
this is causing a lot of headache for me too

the system is unusable at the moment

on GPT4

**Comment by lupuleasa-core** [comment] 2023-04-09 01:27
> > I had to reduce the prompt to 2000 words and told it to accept user input.
> 
> I've been wondering if the core problem is simply asking the model to do too much at once. Perhaps the different functionalities (task planning, criticism, execution, etc) need to be broken up into separate calls (or agents). And I'd go even further to suggest that perhaps forcing replies to be in json is asking to much and makes the functionality fragile. I see BabyAGI as a good reference for an alternative approach like this.
> 
> Of course this is a significant change but I think this is where the evidence is leading...

Yeah, I'm gonna try babyAGI in the meanwhile, the whole prompting chain is unstable in autoGPT

**Comment by Adrien2112** [comment] 2023-04-09 15:13
GPT4 is much better at giving answers respecting a certain syntax.

It has been demonstrated that the error rate on inforced rules from GPT4 is much lower than gpt-3.5

Since the syntax must respect some JSON format, we should probably find an other solution to enforce this syntax, either with hard coding for gpt3.5 or switching to gpt4 for this syntax rule

**Comment by Adrien2112** [comment] 2023-04-09 15:17
Also, we could also use regex to retrieve the info from the JSON, since often what is missing in the answer is often minor: eg some columns, or comas, etc

**Comment by jantic** [comment] 2023-04-09 15:52
> Also, we could also use regex to retrieve the info from the JSON, since often what is missing in the answer is often minor: eg some columns, or comas, etc
> 
> 

Doesn't that defeat the purpose of using json?

**Comment by Adrien2112** [comment] 2023-04-09 16:00
it could be a fallback solution to reduce the error rate when the json isn't properly formatted

**Comment by KingRekter** [comment] 2023-04-09 18:27
An  example approach what to do with json format errors

`while True:
    try:
        result = json.loads(s)   # try to parse...
        break                    # parsing worked -> exit loop
    except Exception as e:
        # "Expecting , delimiter: line 34 column 54 (char 1158)"
        # position of unexpected character after '"'
        unexp = int(re.findall(r'\(char (\d+)\)', str(e))[0])
        # position of unescaped '"' before that
        unesc = s.rfind(r'"', 0, unexp)
        s = s[:unesc] + r'\"' + s[unesc+1:]
        # position of correspondig closing '"' (+2 for inserted '\')
        closg = s.find(r'"', unesc + 2)
        s = s[:closg] + r'\"' + s[closg+1:]
print result`

[](https://stackoverflow.com/questions/18514910/how-do-i-automatically-fix-an-invalid-json-string)

**Comment by KingRekter** [comment] 2023-04-09 18:35
> @KingRekter Good spot! Which script are you referring to?
> 
> Let's get this fixed!

Basically near where you digest the response from chatGPT api ,aka not far downstream .
I am afk for a few , otherwise i would have provided you a much more detailed answer.. sorry

**Comment by Adrien2112** [comment] 2023-04-09 19:12
Hi @Torantulino, is it possible to give me write access to the repo so I can make a push + PR of my branch to fix the issue ?

**Comment by nithronium** [comment] 2023-04-09 22:27
Best solution for now seems to be check if returned response is a valid JSON, if not, re-send the request prompt with "I specifically asked you to send response in the JSON format I asked, please fix your response and send in the format I want without adding anything, my prompt was: [INSERT PREVIOUS PROMPT]" and try this until it returns a valid JSON and then use that JSON in the app. Aside from checks done on JSON parsing, there's not much to do if response is not containing a valid JSON and bot will be breaking all the time.

**Comment by dahifi** [comment] 2023-04-10 13:07
> 

that's actually really brilliant, we just put a try catch block on that line and SEND IT BACK.

**Comment by tdaubs** [comment] 2023-04-13 17:13
> Best solution for now seems to be check if returned response is a valid JSON, if not, re-send the request prompt with "I specifically asked you to send response in the JSON format I asked, please fix your response and send in the format I want without adding anything, my prompt was: [INSERT PREVIOUS PROMPT]" and try this until it returns a valid JSON and then use that JSON in the app. Aside from checks done on JSON parsing, there's not much to do if response is not containing a valid JSON and bot will be breaking all the time.

If the response is not valid and it gets sent back until it is... wouldn't that possibly put it in an endless loop?

**Comment by Pachebel** [comment] 2023-04-13 17:50
I was having the same error here. I just typed: 'fix your code' and it stopped lol

**Comment by EdBen97** [comment] 2023-04-16 13:29
> I seem to be getting much better json generation behavior after I change this in prompt.txt:
> 
> From this:
> 
> > You should only respond in JSON format as described below.
> 
> To this:
> 
> > You should only respond in JSON format as described below. Note that all of these fields are mandatory in the schema.
> 
> I'm wondering if others see the same results....

I am sorry for the stupid question, but where is prompt.txt located and do anyone have documentation on how to configure this file?

**Comment by jaredwideman** [comment] 2023-04-16 14:20
> > I seem to be getting much better json generation behavior after I change this in prompt.txt:
> > From this:
> > > You should only respond in JSON format as described below.
> > 
> > 
> > To this:
> > > You should only respond in JSON format as described below. Note that all of these fields are mandatory in the schema.
> > 
> > 
> > I'm wondering if others see the same results....
> 
> I am sorry for the stupid question, but where is prompt.txt located and do anyone have documentation on how to configure this file?

@EdBen97 Not stupid, couldn't find it either. However, I found "You should only respond in JSON format as described below" in promptgenerator.py, so I assume that's what they're referring to.

**Comment by michaljaszczuk** [comment] 2023-04-16 16:04
> I have had a lot of success with explicitly telling it to only respond in valid JSON, with no additional instructions. Not token efficient but it's been working consistently for me so far.
> 
> ```
> {...}
> 
> PERFORMANCE EVALUATION:
> 
> 1. Review and analyze your actions to ensure you are performing to the best of your abilities. 
> 2. Constructively self-criticize your big-picture behavior constantly.
> 3. Reflect on past decisions and strategies to refine your approach.
> 4. Every command has a cost, so be smart and efficient. Aim to complete tasks in the least number of steps.
> 
> CRITICAL! You may only respond in JSON format as described below. Go carefully and step by step. 
> Do not output any additional instructions outside of the JSON format. Under no circumstances should your response deviate from valid JSON format.
> 
> RESPONSE FORMAT:
> {
>     "thoughts":
>     {
>         "text": "thought",
>         "reasoning": "reasoning",
>         "plan": "- short bulleted\n- list that conveys\n- long-term plan",
>         "criticism": "constructive self-criticism",
>         "speak": "thoughts summary to say to user"
>     },
>     "command": {
>         "name": "command name",
>         "args":{
>             "arg name": "value"
>         }
>     }
> }
> 
> Be absolutely sure the response can be parsed by Python json.loads.  
> ```

Where should I paste the above?

**Comment by jackar** [comment] 2023-04-16 20:17
My AI is back on track after inputting `you aren't responding in the proper JSON format`.

<img width="528" alt="Screenshot 2023-04-16 at 4 17 24 PM" src="https://user-images.githubusercontent.com/2806365/232339770-bf8b0e29-1309-4dac-941f-630006fb772a.png">

**Comment by guppyO** [comment] 2023-04-16 22:48
hey guys I can no longer find prompt.txt in the latest update if autogpt. Where can I put these changes?

**Comment by MicrowaveJak** [comment] 2023-04-16 22:53
> hey guys I can no longer find prompt.txt in the latest update of autogpt. Where can I put these changes?

This is now done by https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/prompt.py at runtime, so you'd make your changes in there

**Comment by guppyO** [comment] 2023-04-16 23:13
What do you recommend I change in prompt.py to no longer receive this error?

I think ill probably end up causing more errors than fixing them x)

**Comment by GoZippy** [comment] 2023-04-18 03:52
This thread is so long and so many have same issue - what is the actual solution?

**Comment by joh-anon** [comment] 2023-04-19 11:49
> I have had a lot of success with explicitly telling it to only respond in valid JSON, with no additional instructions. Not token efficient but it's been working consistently for me so far.
> 
> ```
> {...}
> 
> PERFORMANCE EVALUATION:
> 
> 1. Review and analyze your actions to ensure you are performing to the best of your abilities. 
> 2. Constructively self-criticize your big-picture behavior constantly.
> 3. Reflect on past decisions and strategies to refine your approach.
> 4. Every command has a cost, so be smart and efficient. Aim to complete tasks in the least number of steps.
> 
> CRITICAL! You may only respond in JSON format as described below. Go carefully and step by step. 
> Do not output any additional instructions outside of the JSON format. Under no circumstances should your response deviate from valid JSON format.
> 
> RESPONSE FORMAT:
> {
>     "thoughts":
>     {
>         "text": "thought",
>         "reasoning": "reasoning",
>         "plan": "- short bulleted\n- list that conveys\n- long-term plan",
>         "criticism": "constructive self-criticism",
>         "speak": "thoughts summary to say to user"
>     },
>     "command": {
>         "name": "command name",
>         "args":{
>             "arg name": "value"
>         }
>     }
> }
> 
> Be absolutely sure the response can be parsed by Python json.loads.  
> ```

This seems to have fixed it for me(GPT-4). Thanks!

**Comment by CSUN1997** [comment] 2023-04-20 14:38
> hey guys I can no longer find prompt.txt in the latest update of autogpt. Where can I put these changes?

In autogpt/promptgenerator.py.

**Comment by esd100** [comment] 2023-04-24 00:59
this is definitely not clear. what is the update that needs to be put into promptgenerator.py and where exactly does it need to be put.

**Comment by CSUN1997** [comment] 2023-04-24 17:47
I tried the latest stable release, and the errors are gone. So for anyone who is still troubled by this error, please try downloading the latest stable version.

**Comment by pedromartip** [comment] 2023-04-27 09:36
> Can anyone with GPT4 access confirm the prompt works for 4 but not 3.5?

I'm using GPT4 and that error happens all the time that I input a feedback

**Comment by lc0rp** [comment] 2023-06-12 11:32
Closing as duplicate of #1407

**Closed by lc0rp** 2023-06-12 11:32 UTC
Labels: invalid_json
