### ISSUE TITLE
1046 Failed to read descriptor from node connection

### ISSUE THREAD

**Issue by ray2033** [Significant-Gravitas/Auto-GPT#2057] opened 2023-04-17 02:08 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

[9940:11008:0417/100055.298:ERROR:device_event_log_impl.cc(222)] [10:00:55.297] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)

### Current behavior 😯

Unable to get information from web page

### Expected behavior 🤔

NEXT ACTION:  COMMAND = google ARGUMENTS = {'input': 'how to create amazon associates account and register for product advertising api'}
SYSTEM:  Command google returned: Error: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### Your prompt 📝

```yaml
# Paste your prompt here
```
Role:  Make a market research about smart lock in USA in 2022
Goals: ['top 10 smart lock product', 'market research report', "user's pain point"]
Continue (y/n): n
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: GG
GG here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
GG is: Do a market research on smart home products on amazon US station
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Discover the products with the fastest growth rate and the most favorable comments from users in the past six months
Goal 2: Research the approximate range of profit margins and production costs for these products
Goal 3: Save all of the above to "amazon.txt"

**Comment by Monkey-Bo** [comment] 2023-04-17 02:28
我也是一样的问题

**Comment by LPanic** [comment] 2023-04-17 09:19
I have the same issue:

[14156:15060:0417/111559.958:ERROR:device_event_log_impl.cc(222)] [11:15:59.957] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device connected to the system is not functioning. (0x1F)

**Comment by yuanjiayu123456** [comment] 2023-04-18 01:42
me too

**Comment by Kbediako** [comment] 2023-04-18 09:09
Same issue here

**Comment by dfatih** [comment] 2023-04-18 17:10
Me Too. It is stuck in the loop. Opening Chrome, analyzing the page but can not enter words .

DevTools listening on ws://127.0.0.1:58079/devtools/browser/bb747e49-3486-4f17-b567-5b486e7b9129
Text length: 1301 characters
Adding chunk 1 / 1 to memory
Summarizing chunk 1 / 1
[5784:1632:0418/190745.871:ERROR:device_event_log_impl.cc(222)] [19:07:45.871] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[5784:1632:0418/190745.876:ERROR:device_event_log_impl.cc(222)] [19:07:45.876] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
Added chunk 1 summary to memory
Summarized 1 chunks.
SYSTEM:  Command browse_website returned: ("Answer gathered from website: The text does not provide information on relevant keywords and filters for searching scientific papers related to Personalized Geospatial Conditional Planning for Daily Activities on Google Scholar. \n \n Links: [' (javascript:void(0))', ' (javascript:void(0))', ' (javascript:void(0))', ' (https://scholar.google.com/schhp?hl=de&as_sdt=0,5)', 'Mein Profil (https://scholar.google.com/citations?hl=de)']", <selenium.webdriver.chrome.webdriver.WebDriver (session="09634d448772fc0f67caa3f8800beb96")>)
 THOUGHTS:  I will now use my long-term memory to recall some relevant keywords and filters for searching scientific papers related to Personalized Geospatial Conditional Planning for Daily Activities on Google Scholar. Some possible keywords and filters include: personalized geospatial planning, activity-based planning, optimization techniques, real-time information, environmental impact, and time-saving. I will use these keywords and filters to search for relevant papers on Google Scholar and save the information to a file.
REASONING:  Since I was not able to find relevant keywords and filters on Google Scholar, I will use my long-term memory to recall some possible keywords and filters. These keywords and filters will help me narrow down the search results and find relevant papers on the topic.
PLAN:
-  Use relevant keywords and filters to search for scientific papers related to Personalized Geospatial Conditional Planning for Daily Activities on Google Scholar
-  Save the relevant information to a file
CRITICISM:  I need to make sure that the information I gather is relevant and reliable. I also need to be careful not to spend too much time on one source or paper.
SPEAK:  I will now use my long-term memory to recall some relevant keywords and filters for searching scientific papers related to Personalized Geospatial Conditional Planning for Daily Activities on Google Scholar. Once I have found relevant papers, I will save the
 information to a file.
Attempting to fix JSON by finding outermost brackets
Apparently json was fixed.
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://scholar.google.com/', 'question': 'What scientific papers related
 to Personalized Geospatial Conditional Planning for Daily Activities can I find using the keywords and filters: personalized geospatial planning, activity-based planning, optimization techniques, real-time information, environmental impact, and time-saving?'}

DevTools listening on ws://127.0.0.1:58114/devtools/browser/220b1684-0004-413b-ae90-f6d2e784600a
Text length: 1301 characters
Adding chunk 1 / 1 to memory
Summarizing chunk 1 / 1
[19540:29324:0418/190845.817:ERROR:device_event_log_impl.cc(222)] [19:08:45.817] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[19540:29324:0418/190845.822:ERROR:device_event_log_impl.cc(222)] [19:08:45.822] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
Added chunk 1 summary to memory
Summarized 1 chunks.
SYSTEM:  Command browse_website returned: ("Answer gathered from website: The text does not provide an answer to the question. It is a search engine or database interface with options for advanced search and personalization features. \n \n Links: [' (javascript:void(0))', ' (javascript:void(0))', ' (javascript:void(0))', ' (https://scholar.google.com/schhp?hl=de&as_sdt=0,5)', 'Mein Profil (https://scholar.google.com/citations?hl=de)']", <selenium.webdriver.chrome.webdriver.WebDriver (session="d7af002610ae131322fcd4cfc452bab8")>)

**Comment by hitsx** [comment] 2023-04-19 01:24
I solved the problem by add one line:
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
in file:
    autogpt\commands\web_selenium.py
right after this line:
    options = options_available[CFG.selenium_web_browser]()

**Comment by ntindle** [comment] 2023-04-23 03:59
#1949

**Comment by ntindle** [comment] 2023-04-23 04:00
Dupe of #1949

**Closed by ntindle** 2023-04-23 04:00 UTC

**Comment by bhanumant** [comment] 2023-05-09 12:04
I am facing 1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F) this issue please help
