### ISSUE TITLE
Memory .json file is cleared if AutoGPT is exited or crashes

### ISSUE THREAD

**Issue by Slapbox** [Significant-Gravitas/Auto-GPT#4099] opened 2023-05-11 02:09 UTC
It's not clear from the available docs whether this is expected behavior. Every time I run autogpt it starts entirely from scratch on its task. Other files in the workspace are not lost or cleared though.

**Comment by suparious** [comment] 2023-05-11 03:06
I think that the persistent memory is disabled until v0.4.0

if you use Redis, you can try setting `WIPE_REDIS_ON_START=False`

**Comment by Boostrix** [comment] 2023-05-11 07:04
for the time being, there is no proper persistence scheme - just several disconnected parts at attempting to improve the situation a little, but there's no checkpointing support - neither are there persistent workspaces in between different sessions of agents.

In other words, a new agent may encounter leftovers from previous sessions, but is unlikely to make heads and tails of those - it won't know what it created, why it created stuff or what the files were that you were provided.

I've begun tinkering with different experiments to improve the situation a little by at least providing sufficient contextual information to the new agent - but once you think about it, the very instant you want agents to be able to suspend/resume their work, you are also in the realms of task management and planning - for instance, it may create a parser/validator to parse some file, but the new instance has currently no way of knowing how far it progress with that task, or how to use the tool if it succeeded.

That is one of the reasons why I have arrived at the conclusion that we need not only a persistence scheme in  place, but also need to use this in conjunction with planning, so that recursively defined plans of actions that generate artefacts, are also tracked and can be reused by future instances.

It really is an interesting problem once you think about it.

**Comment by Boostrix** [comment] 2023-05-15 22:39
closing for now, not to discourage discussion - but it's not a bug per se, simply a missing feature, but one that is being worked on - if in doubt, check out discord to learn more.

**Closed by Boostrix** 2023-05-15 22:39 UTC
