### ISSUE TITLE
Having issues running python -m autogpt

### ISSUE THREAD

**Issue by davidscode1414** [Significant-Gravitas/Auto-GPT#2439] opened 2023-04-18 21:13 UTC
This is the error message I receive when running prompt
Warning: The file 'auto-gpt.json' does not exist. Local memory would not be saved to a file.

**Comment by jtgsystems** [comment] 2023-04-18 21:35
I get that too, and without that, it wouldn't work correctly. 

we need a script to allow permissions for all folders and apply whatever permissions the system maybe lack so it will work on anything.

**Comment by Pwuts** [comment] 2023-04-19 15:52
Closing as duplicate of #1073

**Closed by Pwuts** 2023-04-19 15:52 UTC

**Comment by PhilosopherChild** [comment] 2023-04-19 20:56
This is different from #1073 though. This involves the issue with .json but it also has an issue with python -m autogpt being returned instead of continuous dialogue
