### ISSUE TITLE
browse_website -> Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by moltra** [Significant-Gravitas/Auto-GPT#2304] opened 2023-04-18 03:52 UTC
Is there a reason that everything says to run this is "docker-compose run auto-gpt".  This does run and works great, with a few limitations.  The way I understand it is that "docker-compose run auto-gpt" does not create any ports specified in the docker compose file and this would prevent accessing it from a separate computer on the network.  The Docker documentation does not say that it prevents creating Volumes, but I tried the new Docker-compose file from another issue I was referred to #1843.  None of the volumes were created.  I also was getting errors that chrome could not open, and that the files were not 

SYSTEM: Command browse_website returned: Error: Message: unknown error: Chrome failed to start: exited abnormally. (chrome not reachable) (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x55ee1c42ffe3 <unknown> #1 0x55ee1c16ed36 <unknown> #2 0x55ee1c197b20 <unknown> #3 0x55ee1c193a9b <unknown> #4 0x55ee1c1d5af7 <unknown> #5 0x55ee1c1d511f <unknown> #6 0x55ee1c1cc693 <unknown> #7 0x55ee1c19f03a <unknown> #8 0x55ee1c1a017e <unknown> #9 0x55ee1c3f1dbd <unknown> #10 0x55ee1c3f5c6c <unknown> #11 0x55ee1c3ff4b0 <unknown> #12 0x55ee1c3f6d63 <unknown> #13 0x55ee1c3c9c35 <unknown> #14 0x55ee1c41a138 <unknown> #15 0x55ee1c41a2c7 <unknown> #16 0x55ee1c428093 <unknown> #17 0x7faf347e9ea7 start_thread

SYSTEM:  Command read_file returned: Error: [Errno 2] No such file or directory: '/home/appuser/auto_gpt_workspace/search_results.txt'

Not sure if these are related or not.  If not I will split these items into separate issues.

**Comment by Pwuts** [comment] 2023-04-18 04:55
I'm not sure what's going on for you, but the volume mounts generally work fine using `docker-compose run`

**Comment by ntindle** [comment] 2023-04-18 08:44
Unless your docker compose adds a selenium standalone chrome instance, I'd be pretty surprised if that worked in the container.

**Comment by k-boikov** [comment] 2023-04-18 12:25
Might be fixed with https://github.com/Significant-Gravitas/Auto-GPT/pull/1473

**Comment by k-boikov** [comment] 2023-04-18 12:32
Similar to https://github.com/Significant-Gravitas/Auto-GPT/issues/1641

**Comment by Pwuts** [comment] 2023-04-18 18:50
Closing as duplicate of #1641

**Closed by Pwuts** 2023-04-18 18:50 UTC
Labels: bug, function: browse
