### ISSUE TITLE
Ability to use LLaMA models so we dont have to pay openai api?

### ISSUE THREAD

**Issue by mastachef** [Significant-Gravitas/Auto-GPT#438] opened 2023-04-07 22:53 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

https://github.com/facebookresearch/llama

Would it be possible to make this run with this model so we can run it locally rather than having to pay for openai api which is quite spendy.

**Comment by keenborder786** [comment] 2023-04-08 00:27
This seems interesting. I will have a look at it and will try to come up with a solution.

**Comment by keenborder786** [comment] 2023-04-08 00:27
This seems interesting. I will have a look at it and will try to come up with a solution.

**Comment by pdolinic** [comment] 2023-04-08 01:14
Would be the most awesome thing ever, plus we would own the data.

**Comment by igorbarshteyn** [comment] 2023-04-08 01:54
Absolutely agree. I forked this and tried to slot in https://pypi.org/project/llama-cpp-python/ bindings in place of the OpenAI calls in llm-utils.py, but it turned out to be way more complex than that, and unfortunately I don't have the time :(

**Comment by pmb2** [comment] 2023-04-08 05:27
> Would be the most awesome thing ever, plus we would own the data.
> 
> I would suggest plugging https://github.com/lm-sys/FastChat in if someone has the skills to do so.

This is the way.

**Comment by nponeccop** [comment] 2023-04-08 08:43
Duplicate of #414

**Comment by erkkimon** [comment] 2023-04-08 19:51
Indeed, this would make sense also in cyber security point of view.

**Comment by babycommando** [comment] 2023-04-08 22:42
GPT4all is great tho
https://github.com/nomic-ai/gpt4all

**Comment by DifferentialityDevelopment** [comment] 2023-04-09 00:19
I'm fairly familiar now with the process of loading the vicuna 13b model, and using it, the thing is that these llama models are totally reliant on prompt engineering, but they do have the capability to act like a reasoner, act like a criticizer etc so it's do-able.
Getting it to run locally is also not totally too hard to do and you could spawn a local API endpoint to it such as to replace the calls to OpenAI with calls to your local vicuna model.
The best thing IMO of using these models instead of OpenAI's GPT is that there is zero cost if you run it locally, my GTX 3060 with 12gb vram can run a 13b model locally, and i've heard the 30b 4bit quantized model can run on a 24gb gpu.

I'm actually making use of the vicuna 13b 4bit quantized 128g model for my game instead of relying on OpenAI's gpt3.5-turbo,
as that would've just made my game totally uneconomical to play :')

**Comment by keldenl** [comment] 2023-04-09 06:37
> Absolutely agree. I forked this and tried to slot in https://pypi.org/project/llama-cpp-python/ bindings in place of the OpenAI calls in llm-utils.py, but it turned out to be way more complex than that, and unfortunately I don't have the time :(

I'm trying exactly this but ran into issues with the embedding, getting the following error:
```
openai.error.APIError: Invalid response object from API: '{"detail":[{"loc":["body","input"],"msg":"str type expected","type":"type_error.str"}]}' (HTTP response code was 422)
```

Seems like `llama-cpp-python` only supports string input for embeddings? I don't know much about embeddings so I'm kinda confused (somebody smart pls help)

I modified the `get_ada_embedding` function to pass in a `text` instead of `[text]` and it seemed like it might've created the embedding (i printed it), but perhaps incorrectly? 
```
def get_ada_embedding(text):
    text = text.replace("\n", " ")
    return openai.Embedding.create(input=text, model="<YOUR_MODEL_HERE>")["data"][0]["embedding"]
```

Here's the error I'm getting instead:
```
pinecone.core.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Sun, 09 Apr 2023 06:29:29 GMT', 'x-envoy-upstream-service-time': '1', 'content-length': '110', 'server': 'envoy'})
HTTP response body: {"code":3,"message":"Query vector dimension 5120 does not match the dimension of the index 1536","details":[]}
```

**Comment by hanskraut31312312** [comment] 2023-04-09 15:32
They seem not removetly good enought. Maybe "Vicuna" or "gpt4all" for very simple task to create extra agents with preprogrammed clear outlines: Format [here date and time], [here this] [heare that] but it seems at least chatGPT3.5t is nessesary

**Comment by alreadydone** [comment] 2023-04-09 22:13
@keldenl  Looks like you're using [LLaMA 13B with embedding dimension 5120](https://huggingface.co/deerslab/llama-7b-embeddings#quantitative-analysis). PineconeMemory embedding dimension is [hardcoded as 1536](https://github.com/Torantulino/Auto-GPT/blob/48451e305a1faec53503ef397c078cd8cda0abb4/scripts/memory.py#L22) so you probably need to change it.

**Comment by emskiemre** [comment] 2023-04-13 19:03
@DifferentialityDevelopment maby you can explain how this works ? https://github.com/BillSchumacher/Auto-Vicuna

I've been trying it, but wont work ...

**Comment by Qoyyuum** [comment] 2023-04-16 12:58
Closing this issue in favor of and duplicate to #567

**Closed by Qoyyuum** 2023-04-16 12:58 UTC
Labels: enhancement, help wanted, ai_model_limitation, needs discussion, potential plugin
