### ISSUE TITLE
Error:          Traceback (most recent call last): File "/Users/gals/Auto-GPT/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/Users/gals/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found

### ISSUE THREAD

**Issue by galscode** [Significant-Gravitas/Auto-GPT#912] opened 2023-04-12 05:41 UTC
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Every time i give the model human feedback this error occurs:

Error:        
 Traceback (most recent call last): File "/Users/gals/Auto-GPT/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/Users/gals/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not foundEvery time

### Expected behavior 🤔

Process the feedback and act accordingly

### Your prompt 📝

```yaml
Input:First build a pinecone index call it auto-gpt-kw-ideas
SYSTEM:  Human feedback: First build a pinecone index call it auto-gpt-kw-ideas
Error:        
 Traceback (most recent call last): File "/Users/gals/Auto-GPT/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/Users/gals/Auto-GPT/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found
```

**Comment by richbeales** [comment] 2023-04-12 06:19
dupe of https://github.com/Torantulino/Auto-GPT/issues/793

**Closed** 2023-04-18 03:32 UTC
