### ISSUE TITLE
What would it need to be able to use llama Cpp API + Custom Functions

### ISSUE THREAD

**Issue by Nrddy** [Significant-Gravitas/Auto-GPT#951] opened 2023-04-12 13:10 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

To help reduce the cost could this be adapted to use the Llama CPP API or KoladAI APi? this would reduce the rate limit and cost of open AI to continually run this.? also what would it take to add exentions so that we can add in some custom function?

**Comment by vandervoortj** [comment] 2023-04-12 13:23
Could use oobabooga/text-generation-webui API and have access to any model compatible with it. I think I heard somebody is already working on it. Realistically though, most models won't be useful. The most promising that I'm aware of atm is Vicuna.

**Comment by Nrddy** [comment] 2023-04-12 13:32
I have that up and running now. though i haven't tried the api. I do see though that he updated the api last night.  I found that https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g is a good model so far... and I have Vicuna too I am comparing them . I know both of them might need a nudge in the right direction but as long as We can get basic process skills then hopefully they will work.. I am just thinking to reduce over all cost. I am curious where in the code i would need to change to use the ooboooga APi.

**Comment by Pwuts** [comment] 2023-04-18 03:37
Closing as duplicate of #25

**Closed by Pwuts** 2023-04-18 03:37 UTC
