### ISSUE TITLE
OpenAI API remote disconnect issues

### ISSUE THREAD

**Issue by lllMBPlll** [Significant-Gravitas/Auto-GPT#2241] opened 2023-04-17 20:50 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

These errors appeared after entering my goals.

### Current behavior 😯

Traceback (most recent call last):
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Auto-GPT-0.2.1\autogpt\__main__.py", line 53, in <module>
    main()
  File "C:\Auto-GPT-0.2.1\autogpt\__main__.py", line 49, in main
    agent.start_interaction_loop()
  File "C:\Auto-GPT-0.2.1\autogpt\agent\agent.py", line 65, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "C:\Auto-GPT-0.2.1\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\Auto-GPT-0.2.1\autogpt\llm_utils.py", line 91, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Users\cwalt\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment] 2023-04-17 21:10
Are you getting the error continuously? Seems like the OpenAI API is aborting the connection. Try again.

**Comment by lllMBPlll** [comment] 2023-04-17 22:13
Unfortunately yes. The same errors keep occurring regardless of what goals are inputted.

**Comment by k-boikov** [comment] 2023-04-17 22:26
Are you in China? Are you using a VPN?
Maybe check this https://github.com/openai/openai-python/issues/56
Unfortunately the issue is not with AutoGPT but with OpenAI and your environment/ISP.

**Comment by dragonmantank** [comment] 2023-04-17 23:31
I just started getting this error over the last hour or so as well. Everything was working "fine" before that (getting other errors, but stuff like the JSON error). I am using the gpt3only flag while I wait for gpt4 API access, if that helps.

**Comment by dragonmantank** [comment] 2023-04-18 15:12
My connection is Spectrum cable internet, midwest, 400mb/12mb, and tends to be very stable. I do notice that it seems to be almost exclusively during unattended sessions (say after something like `y -50`) or potentially long sessions, like after 20 or so minutes of running. It seems worse after after agents are starting to get deployed, and happens on `master` or `stable`.

This makes it almost impossible to actually finish any project now since restarting the bot starts completely over.

**Comment by Pwuts** [comment] 2023-04-18 15:58
Do those errors occur while processing the output of specific commands like `browse_website` or `google`? If so, which?

**Comment by Pwuts** [comment] 2023-04-18 20:41
Partial fix: #214

**Comment by lllMBPlll** [comment] 2023-04-18 21:39
Appreaciate the help all!

@k-boikov, I am currently in CDMX (Mexico City) and was not using a VPN, but I could if needs be. 

@Pwuts, thanks I'll check out #214

**Comment by Pwuts** [comment] 2023-04-20 00:27
@lllMBPlll that PR is currently broken, but we're working on merging it.

**Comment by ntindle** [comment] 2023-04-21 04:34
Fixed via #1537

**Closed by ntindle** 2023-04-21 04:34 UTC
Labels: bug, API access

**Comment by vinodkumartheking** [comment] 2023-04-23 06:24
I am getting the same error even though I use the latest master branch. Any idea on how to fix it.

![image](https://user-images.githubusercontent.com/18139750/233823509-b3fee91f-ac07-4d3e-851a-3c6af6f19fda.png)
