### ISSUE TITLE
Error fails to change the code inside a python file

### ISSUE THREAD

**Issue by karingijs2727** [Significant-Gravitas/Auto-GPT#2357] opened 2023-04-18 09:48 UTC
SYSTEM:  Command write_to_file returned: Error: File has already been updated.
The role of AI was to generate discord bot code he made a python file but when the AI wanted to change or add code to it
i got this error above so the AI can't expand the code

**Comment by Pwuts** [comment] 2023-04-18 16:36
Closing as duplicate of #1891

**Closed by Pwuts** 2023-04-18 16:36 UTC
