### ISSUE TITLE
Actor-Critic Methods or "What if Auto-GPT could evaluate and improve its plans?"

### ISSUE THREAD

**Issue by jhouchin** [Significant-Gravitas/Auto-GPT#419] opened 2023-04-07 20:25 UTC
### Duplicates

- [x] I have searched the existing issues

### Summary 💡

This suggestion is loosely inspired by [Actor-Critic Methods](https://huggingface.co/deep-rl-course/unit6/introduction) in Reinforcement Learning.

Essentially, this would involve two agents that work in tandem:
Actor - Essentially Auto-GPT as it exists now. The only difference is an additional step between coming up with a plan and acting on that plan.
Critic - Evaluates the plans that the Actor outputs, but unlike Actor-Critic in RL, it directly gives the Actor suggestions on how to improve the plan. (Leveraging the fact that GPT-4 is an LLM)

I'm imagining a flow like this:

1. Actor comes up with a plan, but does not execute it right away like Auto-GPT does now.
2. Actor outputs an explanation of the plan to the Critic.
3. Critic evaluates the plan and outputs a suggestion of how to improve the plan. (If it can think of one)
4. Actor modifies the plan based on the Critic's suggestion.
5. (Optionally) loop through 2-4 until both Actor and Critic agree the plan can no longer be improved.
6. Actor executes the plan.
7. Repeat as per regular Auto-GPT.

Ideally, the Actor and Critic would be separate instances of GPT-4. I can imagine there's a way to make it work within a single instance with some clever prompting, but my gut feeling is that two specialized agents would outperform one general-purpose agent. (Testing both options might be a good idea though, since 2 agents means potentially double the API costs)

I would try to implement all this myself, but sadly I don't have API access.

### Motivation 🔦

This method may allow Auto-GPT to essentially "fine-tune" its plans, potentially allowing Auto-GPT to improve itself to a limited degree. Additionally, if the Actor begins to loop and suggest the same plans, the Critic may pick up on this and inform the Actor as such. (This might require specific prompting to the Critic, though)

**Comment by russinet** [comment] 2023-04-08 08:19
I have access to GPT-4 API and I am very interested in your idea. Would you like to discuss this further?

**Comment by Pwuts** [comment] 2023-04-18 01:41
Closing as duplicate of #151. Please add to that issue, or reopen this one if you disagree.

**Closed by Pwuts** 2023-04-18 01:41 UTC
