### ISSUE TITLE
Way to Intervene running progress

### ISSUE THREAD

**Issue by AsaTyr2018** [Significant-Gravitas/Auto-GPT#737] opened 2023-04-10 21:59 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Once a Progress is running it can only be killed with crtl + c 
This kills the whole proccess and you have to enter everything again. 

### Examples 🌈

Starting a Proccess with a relativly simple prompt. once it running the AI kicks in a loop with something like "can´t find a file xyz" but you know that its just a wrong directory its looking. 
Pressing a special Key stops it so that the user can make some adjustments so the AI doesn´t need to move in circles to find the missing file.
Like an additional Prompt that can be enter to correct its path.

### Motivation 🔦

Making a longrun reserche easier to correct once it goes in a wrong direction by adding an additional prompt midway.

**Comment by Pwuts** [comment] 2023-04-18 02:52
Closing as a duplicate of #150, #1472

**Closed by Pwuts** 2023-04-18 02:52 UTC
