### ISSUE TITLE
Azure OpenAI Key Error

### ISSUE THREAD

**Issue by KlayZKZhang** [Significant-Gravitas/Auto-GPT#4607] opened 2023-06-07 04:48 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I can't use Azure gpt in v0.4.0,please help me,thank you.

All packages are installed.
_WARNING:  You do not have access to gpt-3.5-turbo. Setting fast_llm_model to gpt-3.5-turbo._
NEWS:  Welcome to Auto-GPT!

**![屏幕截图 2023-06-07 124525](https://github.com/Significant-Gravitas/Auto-GPT/assets/125565618/2a7acb61-a164-400a-8ab4-e481d7a9da47)**

**After I set the GPT name, goals, etc., I pressed Y and got the following error**

Traceback (most recent call last):
  File "D:\environment\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\environment\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "D:\environment\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\environment\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\environment\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "D:\environment\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\environment\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\environment\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\main.py", line 197, in run_auto_gpt
    agent.start_interaction_loop()
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\agent\agent.py", line 130, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\llm\chat.py", line 193, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\llm\utils\__init__.py", line 53, in metered_func
    return func(*args, **kwargs)
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\llm\utils\__init__.py", line 87, in _wrapped
    return func(*args, **kwargs)
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\llm\utils\__init__.py", line 235, in create_chat_completion
    response = api_manager.create_chat_completion(
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\llm\api_manager.py", line 72, in create_chat_completion
    self.update_cost(prompt_tokens, completion_tokens, model)
  File "C:\Users\87495\Desktop\GPT\Auto-GPT-0.4.0\autogpt\llm\api_manager.py", line 85, in update_cost
    model = model[:-3] if model.endswith("-v2") else model
AttributeError: 'NoneType' object has no attribute 'endswith'

![屏幕截图 2023-06-07 124717](https://github.com/Significant-Gravitas/Auto-GPT/assets/125565618/7768d96b-396f-446f-b351-8a3fb99e0d13)

In the .env file I have the following settings:
OPENAI_API_KEY=my-azure-key
USE_AZURE=True

In the azure.yaml file I have the following settings:
azure_api_type: "azure"
azure_api_base: "https://aaa.openai.azure.com/"
azure_api_version: "2023-03-15-preview"
azure_model_map:
    fast_llm_model_deployment_id: "gpt-35-turbo"
    smart_llm_model_deployment_id: "GPT4Test"
    embedding_model_deployment_id: "text-embedding-ada-002"

ps:To exclude the possibility of entering model name and deploy name, I adjusted the deploy name to match the model name except for GPT4

**Comment by KlayZKZhang** [comment] 2023-06-07 06:45
> I'm encountering the same issue; it appears that the `model` is set to `None` in the `autgpt/llm/api_manager.py file`. I managed to temporarily resolve the problem by changing the line from `self.update_cost(prompt_tokens, completion_tokens, model)` to `self.update_cost(prompt_tokens, completion_tokens, response["model"]`). However, I'm uncertain if this is a long-term solution or just a temporary fix.

Still have WARNING, but it works, thanks for the advice

**Comment by ccdanpian** [comment] 2023-06-07 07:17
I also encountered the same issue, but after changing 'mdel' to 'response["model"]', the problem was not resolved and a new error appeared in the same 'update_cost' function.
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/130242490/d0416ffe-8775-4f39-b20e-36cbca982e42)

**Comment by KlayZKZhang** [comment] 2023-06-08 01:36
#4612 This is the latest known solution

**Comment by lc0rp** [comment] 2023-06-08 02:59
@KlayZKZhang - did you solve this using the fix in issue #4612? 

If so, #4445 was closed without being merged. Would you mind submitting a PR?

Thanks!

**Comment by lc0rp** [comment] 2023-06-08 03:00
Duplicate of #4612

**Comment by lc0rp** [comment] 2023-06-08 03:00
Closing this to track on #4612

**Closed by lc0rp** 2023-06-08 03:00 UTC

**Comment by KlayZKZhang** [comment] 2023-06-08 03:02
> @KlayZKZhang - did you solve this using the fix in issue #4612?
> 
> If so, #4445 was closed without being merged. Would you mind submitting a PR?
> 
> Thanks!

No problem, please feel free to
