### ISSUE TITLE
Python scripts are written incorrectly and contain a literal `\n` instead of an actual carriage return

### ISSUE THREAD

**Issue by claytondukes** [Significant-Gravitas/Auto-GPT#861] opened 2023-04-11 21:25 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

anything requiring script creation

### Current behavior 😯

creates python scripts with literal `\n`

e.g.:

```
#!/usr/bin/env python3
\\nimport subprocess

subprocess.run(['/opt/homebrew/bin/pip3', 'install', 'requests'])
```

### Expected behavior 🤔

should be an actual carriage return

### Your prompt 📝

```yaml
ai_goals:
- Assume you are running on a Mac M1
- assume shell is zshrc
- Assume homebrew is already installed at /opt/homebrew
- Assume ffmpeg is already installed and available at /opt/homebrew/bin/ffmpeg
- use python3 located at /opt/homebrew/bin/python3 for scripts
- use "/opt/homebrew/bin/brew install" if needed
- use "/opt/homebrew/bin/pip3 install" if needed
- all scripts created must be python3, no shell scripts
- save all scripts you create to outputs/
- Using the captions file at inputs/captions.sbv
- Remove the audio from the video
- Rewrite the captions to a more professional tone used for training videos
- create a voiceover from the captions using elevenlabs.io
- for elevenlabs, use the existing ELEVENLABS_API_KEY environment variable
- for elevenlabs, use voice_id "EXAVITQu4va4xN1DfMCL"
- for elevenlabs, documentation for text-to-speach is located at https://api.elevenlabs.io/docs#/text-to-speech
- remove the current audio from the video located at inputs/video.mp4
- Add created voiceover to the video
- save all work to outputs/

**Comment by mencelot** [comment] 2023-04-11 21:36
What version of gpt are you using?

**Comment by claytondukes** [comment] 2023-04-11 21:37
```
SMART_LLM_MODEL=gpt-3.5-turbo
FAST_LLM_MODEL=gpt-3.5-turbo
```

**Comment by mencelot** [comment] 2023-04-11 21:50
I read earlier that the json formatting is meant for gpt 4 not so much lesser models. 

Since the latest update that amends this I find that it does not respond well to user formatting requests, at least using the model we are using, on my m1. 

I let it run on defaults for a hour, no problems. I tell it that chat gpt agents can't search the web and it should rather parse the summary of [specified URL] to them for context instead it breaks. 

NEXT ACTION:  COMMAND = Error: ARGUMENTS = substring not found = endless loop

**Comment by sameerpanjwani** [comment] 2023-04-13 06:34
Facing same issue, extra \n coming in all files generated.

Using

SMART_LLM_MODEL=gpt-3.5-turbo
FAST_LLM_MODEL=gpt-3.5-turbo

**Comment by grahammyers** [comment] 2023-04-13 15:37
When the AI creates a plan, the plan has \n for each line of the bulleted list. This failure of the plan to write out correctly seems to cause my instance to set a Next Action of COMMAND = do_nothing

I am using GPT4 though

**Comment by Pwuts** [comment] 2023-04-18 04:01
Closing as duplicate of #652

**Closed by Pwuts** 2023-04-18 04:01 UTC
