### ISSUE TITLE
Ability to point to private LLM deployments

### ISSUE THREAD

**Issue by vineetvermait** [Significant-Gravitas/Auto-GPT#3610] opened 2023-05-01 07:20 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Instead of charged plan of OpenAI, could we have a plugin/feature where a LLM model like Vicuna or some other model deployed on local/cloud could be used . Something similar to what invoke AI or Automatic1111 SD  web ui.

### Motivation 🔦

I want to bypass the chat GPT costing and use my own LLMs for the same

**Comment by Boostrix** [comment] 2023-05-01 07:51
Please see: #2158

**Comment by MarkSchmidty** [comment] 2023-05-01 11:50
Dupe of #25

**Closed** 2023-05-01 17:42 UTC
