### ISSUE TITLE
Unable to run built docker container: No module named autogpt

### ISSUE THREAD

**Issue by psvensson** [Significant-Gravitas/Auto-GPT#1513] opened 2023-04-15 08:47 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Docker buidl goes perfectly fine, albeit with a lot of warning..

 
docker run -it --env-file=./.env -v ~/auto_gpt_workspace:/app/auto_gpt_workspace autogpt

gives back:

/usr/local/bin/python: No module named autogpt

I have followed the README exactly. This is a checked out master from some minutes ago.

### Current behavior 😯

/usr/local/bin/python: No module named autogpt

### Expected behavior 🤔

It should just run, right?

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Qoyyuum** [comment] 2023-04-15 09:02
The fix is on the way with #1425

https://github.com/Significant-Gravitas/Auto-GPT/pull/1425

**Comment by alessandropalla** [comment] 2023-04-15 09:06
[Fixed](https://github.com/Significant-Gravitas/Auto-GPT/pull/1516)

**Comment by M00NSH0T** [comment] 2023-05-02 17:55
I just encountered this today after trying to run with Docker (latest).

**Comment by M00NSH0T** [comment] 2023-05-02 18:14
I reverted from 0.3 to 0.2.2 and it works. Didn't really dig in much past that, but might be worth somebody checking that the fix didn't get reverted in this new release...

**Comment by samuelbutler** [comment] 2023-05-02 18:36
I'm not able to reproduce your error with 0.3.0 on Linux. Are you using macOS?

![image](https://user-images.githubusercontent.com/45949667/235755085-fec30543-63ab-4f68-8ec0-e17a7e4c3611.png)

**Comment by M00NSH0T** [comment] 2023-05-02 18:37
I'm on Windows

**Comment by badcom** [comment] 2023-05-02 18:39
I'm getting the same error on Windows running on Docker latest version:

"/usr/local/bin/python: No module named autogpt"

**Comment by ppetermann** [comment] 2023-05-02 18:53
@badcom @M00NSH0T what *exact* command are you trying to use to start it?  (the one in the original ticket is not using windows pathes)

**Comment by M00NSH0T** [comment] 2023-05-02 18:55
happens when I run `docker-compose` run --rm auto-gpt` in the directory with the .env and docker-compose.yml files.

**Comment by ppetermann** [comment] 2023-05-02 19:06
@M00NSH0T is that the root directory of auto-gpt 0.3.0, or do you have those files in a different directory?

**Comment by M00NSH0T** [comment] 2023-05-02 19:09
no I put those files in a different directory. Just followed what's here: https://docs.agpt.co/setup/#set-up-with-docker

**Comment by hackern0v1c3** [comment] 2023-05-02 19:11
I also have the same issue on windows.

compose file
![image](https://user-images.githubusercontent.com/22823269/235762184-2b8aecf4-d57e-4712-ba43-4cf71bd4a7a2.png)

![image](https://user-images.githubusercontent.com/22823269/235762662-fbd323f7-b386-47ca-82cf-b110f0f30b3f.png)

**Comment by bartoszc** [comment] 2023-05-02 19:15
same here

**Comment by M00NSH0T** [comment] 2023-05-02 19:17
again note that when I pull and run v0.2.2, I don't get this error `docker pull significantgravitas/auto-gpt:0.2.2`

**Comment by ppetermann** [comment] 2023-05-02 19:22
this is yaml, not xml

mounting . into /app doesn't do much with 0.2.2 as 0.2.2 used a different path, hence your local directory is not overwriting whats in the container, hence it will run - not by design though

**Comment by hackern0v1c3** [comment] 2023-05-02 19:27
> this is yaml, not xml
> 
> mounting . into /app doesn't do much with 0.2.2 as 0.2.2 used a different path, hence your local directory is not overwriting whats in the container, hence it will run - not by design though

Maybe this requires a documentation fix.  I am following the guide here
https://docs.agpt.co/setup/#run-with-docker

It explicitly says to create a docker-compose file with the mount.  But based on your explanation it should not.
![image](https://user-images.githubusercontent.com/22823269/235765763-a697a8b6-5b5b-44dd-818b-23cfd7abfbb6.png)

However the container still fails with a ModuleNotFoundError when I am not mounting the volume.

**Comment by ppetermann** [comment] 2023-05-02 19:28
@hackern0v1c3 as i said thats because 0.2.2 was using other pathes.

the scripts error is related to the production build not including scripts because it assumes you have the folder mounted

**Comment by ppetermann** [comment] 2023-05-02 19:28
yes, i can confirm that the documentation has issues.

**Comment by hackern0v1c3** [comment] 2023-05-02 19:32
Okay thanks for looking and the quick responses.  
What do you suggest that we do to run in docker with 0.3 on windows?  I'm not sure what you mean by "the scripts error is related to the production build not including scripts because it assumes you have the folder mounted" or how I should go about resolving that issue.  Is there a valid docker-compose that we could reference?

**Comment by ppetermann** [comment] 2023-05-02 19:40
@hackern0v1c3 the issue is actually not really windows related, i guess we *nix folk are more on the end of using the source ;)

as for what you can do, the pragmatic way is: download the release, copy your config into the extracted folder, and run it from there - not ideal, but pragmatic.

you can also build the image from the source yourself, but make sure you are building the *dev* variant, as that includes everything vs. only the autogpt folder

**Comment by ppetermann** [comment] 2023-05-02 19:42
https://github.com/ppetermann/Auto-GPT-DockerSetup this is the setup I'm running, which is a bit more complex, but it works, however there might be some pre-existing docker-knowledge required

**Comment by M00NSH0T** [comment] 2023-05-02 19:51
thanks. I'll try that.

**Comment by hackern0v1c3** [comment] 2023-05-02 19:51
Again I appreciate your help.  I'll take a look at these resources.  My feedback would just be that the "Setup with docker" documentation here https://docs.agpt.co/setup/#set-up-with-docker is a bit misleading.  It works for v0.2.2 but not 0.3.  Most likely due to the fact that 0.2.2 was using other paths as you mentioned.  It would be great if the documentation were updated, or at least a warning added that they will only work for 0.2.2 without additional undocumented steps.

**Comment by M00NSH0T** [comment] 2023-05-02 19:58
I second that... I had it all running fine yesterday in a dedicated conda environment I setup. Just downloaded the repo and it worked great. Unfortunately this morning, I updated Docker Desktop which I'd been putting off for a while, and ever since AutoGPT just keeps trying to install modules (like requests, beautifulsoup, etc.) over and over without it affecting whatever Docker container it's referencing.  I figured I'd go back and reinstall using Docker hoping that would solve the infinite loop issue with it not actually being able to install dependencies. 

But that led me here... yeah an update to the documentation would definitely be nice. I appreciate you sending that link to your docker setup in the meantime @ppetermann . Thank you

**Comment by ppetermann** [comment] 2023-05-02 20:12
I'm working on an update, just not something that appears of thin air ;)

**Comment by hackern0v1c3** [comment] 2023-05-02 20:34
It looks like someone has a pull request in to fix this already #3706
I can build an image locally and run .0.3.0 by adding the additional two lines from that pull request to the dockerfile.  That should get me by until it's merged and the dockerhub image is updated.

Didn't mean to offend with the documentation comment.  I know you guys have your hands full.  Just trying to provide constructive feedback.

**Comment by Pwuts** [comment] 2023-05-02 20:51
> guys, that docker-compose.yml mounts the local directory into the container, if you are in another directory, obviously the autogpt subfolder won't be mounted in. so either you adjust the docker-compose.yml to not mount . to /app OR you run it from a folder that actually has the source.

Thanks for catching that, I think we should probably remove the volume mount from that template `docker-compose.yml`

**Comment by alex-s-gardner** [comment] 2023-05-02 22:27
@hackern0v1c3 does your solution require  following the [git setup](https://docs.agpt.co/setup/), modifying the [Docker file](https://github.com/Significant-Gravitas/Auto-GPT/blob/master/Dockerfile), then building the docker image?

**Closed** 2023-05-02 23:08 UTC
Labels: bug, setup, docker

**Comment by alex-s-gardner** [comment] 2023-05-02 23:10
For anyone that comes next and is using MacOS:

At the terminal:
1. download [Docker](https://docs.docker.com/desktop/install/mac-install/) if you don't already have it
2. Navigate to where you want the Auto-GPT repository folder to be created, for me this was `cd Documents/GitHub/`
3. Clone repository `git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git`
4. cd into new folder `cd Auto-GPT`
5. add these to lines to the `Dockerfile`, located at the top of the the new Auto-GPT directory,  directly below `ONBUILD COPY autogpt/ ./autogpt`:
   `NBUILD COPY scripts/ ./scripts`
    `ONBUILD COPY plugins/ ./plugins`
6. Specify your secrete openAI key in the variable `OPENAI_API_KEY` in the .env.template file
7. copy  `.env.template` to `.env`: `cp .env.template .env`
8. build docker image `docker compose build auto-gpt` NOTE: mac does not use `docker-compose` syntax
9. run docker image `docker compose run --rm auto-gpt` NOTE: mac does not use `docker-compose` syntax

**Comment by pearlmary** [comment] 2023-06-09 07:59
> 9\. docker compose run --rm auto-gpt

After this step, it hangs forever. build is successful.
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/29123795/e4bff339-d6cb-49f1-ac2b-0facfaa13011)

**Comment by pearlmary** [comment] 2023-06-09 08:11
![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/29123795/52486a19-f67c-4bfa-8bd0-b869485af26c)
two different versions of docker compose?
