### ISSUE TITLE
Missing Latest tag on Docker Hub image

### ISSUE THREAD

**Issue by aangelinsf** [Significant-Gravitas/Auto-GPT#3592] opened 2023-04-30 19:57 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Other (Please specify in your problem)

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

The instructions indicate to use the latest tag but this give an error:
```
docker pull significantgravitas/auto-gpt
Using default tag: latest
Error response from daemon: manifest for significantgravitas/auto-gpt:latest not found: manifest unknown: manifest unknown

```

### Expected behavior 🤔
The image should be pulled.

### Workaround
This works:
`docker pull significantgravitas/auto-gpt:0.2.2 `

Also update the line in docker-compose.yml:
```
services:
  auto-gpt:
    image: significantgravitas/auto-gpt:0.2.2
```

### Suggested Solution
Add the `latest` tag to the Docker Hub release.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment] 2023-05-01 01:53
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/3403

**Closed by k-boikov** 2023-05-01 01:53 UTC
