### ISSUE TITLE
Allow human input

### ISSUE THREAD

**Issue by estiens** [Significant-Gravitas/Auto-GPT#779] opened 2023-04-11 08:28 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

A new command "Ask for input or clarification" - if running autonomously could stop and wait a specified number of seconds before going on by itself, but many times some steering is very beneficial...

### Examples 🌈

command: "ask_user", "Ask user for clarification on something or for more context."

### Motivation 🔦

So many times it gets tuck in loops that it can be nudged out of, and I would expect that a lot of the value proposition will come from both some autonomy and some human steering

**Comment by mencelot** [comment] 2023-04-11 09:40
Yes it sometimes gets a bit off track and in these early stages it also sometimes goes into a unbreakable loop in continuous mode. Leaving me with the only option to control+c. Sometimes when I return it is still in a erroneous state resulting in the need to start from scratch.

**Comment by estiens** [comment] 2023-04-13 16:47
Adding just a general "Ask for more context or next steps" command seems to be intelligently used if you are going turn by turn, I think they key here is managing what the break out of continuous mode looks like. For example, wait indefinitely could be one option - ask for user input and if not received within X time, take my own best guess could be another

**Comment by Pwuts** [comment] 2023-04-18 04:05
Closing as duplicate of #1472 / #150. Please add to those issues. :)

**Closed by Pwuts** 2023-04-18 04:05 UTC
