### ISSUE TITLE
why it shows " This model's maximum context length is 8191 tokens ? "

### ISSUE THREAD

**Issue by samual30000** [Significant-Gravitas/Auto-GPT#2366] opened 2023-04-18 11:34 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Current behavior 😯
why it shows " This model's maximum context length is 8191 tokens ? "
i make a debug and see the content is short. WHY it shows that error ? 

```console
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y -20
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/sam/Auto-GPT/autogpt/__main__.py", line 86, in <module>
    main()
  File "/sam/Auto-GPT/autogpt/__main__.py", line 82, in main
    agent.start_interaction_loop()
  File "/sam/Auto-GPT/autogpt/agent/agent.py", line 170, in start_interaction_loop
    self.memory.add(memory_to_add)
  File "/sam/Auto-GPT/autogpt/memory/redismem.py", line 94, in add
    vector = create_embedding_with_ada(data)
  File "/sam/Auto-GPT/autogpt/llm_utils.py", line 174, in create_embedding_with_ada
    return openai.Embedding.create(
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 15117 tokens (15117 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.
root@CH-202203180108:/sam/Auto-GPT#
```

### Steps to reproduce 🕹

```py
# Auto-GPT\autogpt\llm_utils.py
def create_chat_completion(
    messages: list,  # type: ignore
    model: str | None = None,
    temperature: float = CFG.temperature,
    max_tokens: int | None = None,
) -> str:
 
    with open("/sam/n/interaction_log.txt", "a", encoding="utf-8") as log_file:
        log_file.write("\n\n---- Interaction ----\n")
        for message in messages:
            if message["role"] == "system":
                log_file.write(f"System: {message['content']}\n")
            elif message["role"] == "user":
                log_file.write(f"User: {message['content']}\n")
            else:
                log_file.write(f"Assistant: {message['content']}\n")
```

/sam/n/interaction_log.txt shows that:
```console
root@CH-202203180108:/sam/n# cat interaction_log.txt


---- Interaction ----
System: You are 45646, xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Your decisions must always be made independently without seeking user assistance. Play to your strengths as an LLM and pursue simple strategies with no legal complications.

GOALS:

1. 1:啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
2. 2:啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
3. 3:啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
4. 4:啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
5. 5:啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊


Constraints:
1. ~4000 word limit for short term memory. Your short term memory is short, so immediately save important information to files.
2. If you are unsure how you previously did something or want to recall past events, thinking about similar events will help you remember.
3. No user assistance
4. Exclusively use the commands listed in double quotes e.g. "command name"

Commands:
1. Google Search: "google", args: "input": "<search>"
2. Browse Website: "browse_website", args: "url": "<url>", "question": "<what_you_want_to_find_on_website>"
3. Start GPT Agent: "start_agent", args: "name": "<name>", "task": "<short_task_desc>", "prompt": "<prompt>"
4. Message GPT Agent: "message_agent", args: "key": "<key>", "message": "<message>"
5. List GPT Agents: "list_agents", args: 
6. Delete GPT Agent: "delete_agent", args: "key": "<key>"
7. Clone Repository: "clone_repository", args: "repository_url": "<url>", "clone_path": "<directory>"
8. Write to file: "write_to_file", args: "file": "<file>", "text": "<text>"
9. Read file: "read_file", args: "file": "<file>"
10. Append to file: "append_to_file", args: "file": "<file>", "text": "<text>"
11. Delete file: "delete_file", args: "file": "<file>"
12. Search Files: "search_files", args: "directory": "<directory>"
13. Evaluate Code: "evaluate_code", args: "code": "<full_code_string>"
14. Get Improved Code: "improve_code", args: "suggestions": "<list_of_suggestions>", "code": "<full_code_string>"
15. Write Tests: "write_tests", args: "code": "<full_code_string>", "focus": "<list_of_focus_areas>"
16. Execute Python File: "execute_python_file", args: "file": "<file>"
17. Generate Image: "generate_image", args: "prompt": "<prompt>"
18. Convert Audio to text: "read_audio_from_file", args: "file": "<file>"
19. Send Tweet: "send_tweet", args: "text": "<text>"
20. Execute Shell Command, non-interactive commands only: "execute_shell", args: "command_line": "<command_line>"
21. Do Nothing: "do_nothing", args: 
22. Task Complete (Shutdown): "task_complete", args: "reason": "<reason>"

Resources:
1. Internet access for searches and information gathering.
2. Long Term memory management.
3. GPT-3.5 powered Agents for delegation of simple tasks.
4. File output.

Performance Evaluation:
1. Continuously review and analyze your actions to ensure you are performing to the best of your abilities.
2. Constructively self-criticize your big-picture behavior constantly.
3. Reflect on past decisions and strategies to refine your approach.
4. Every command has a cost, so be smart and efficient. Aim to complete tasks in the least number of steps.

You should only respond in JSON format as described below 
Response Format: 
{
    "thoughts": {
        "text": "thought",
        "reasoning": "reasoning",
        "plan": "- short bulleted\n- list that conveys\n- long-term plan",
        "criticism": "constructive self-criticism",
        "speak": "thoughts summary to say to user"
    },
    "command": {
        "name": "command name",
        "args": {
            "arg name": "value"
        }
    }
} 
Ensure the response can beparsed by Python json.loads
System: The current time and date is Tue Apr 18 18:41:56 2023
System: This reminds you of these events from your past:
```

**Comment by samual30000** [comment] 2023-04-18 11:38
看起来内容不长啊,手动输入到gpt 3.5,gpt4都能处理的, 为啥显示超了呢

**Comment by k-boikov** [comment] 2023-04-18 11:57
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/2337

**Comment by Pwuts** [comment] 2023-04-18 13:14
@samual30000 what is the last command before that error occurs?

**Comment by broose42** [comment] 2023-04-18 13:39
@Pwuts 

I had mine try to command_search to search the whole of its working files then cut out due to token limit being exceeded. 


openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 8763 tokens (8763 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.



Presume if it tries to do a large pull it cuts out on GPT 3.5 at least. Not sure about GPT 4. 

Maybe limit the tokens requested for each prompt?

**Comment by Pwuts** [comment] 2023-04-18 14:12
Closing as duplicate of #1841. cc @broose42

@samual30000 feel free to add to #1841 with your prompt+log.

**Closed by Pwuts** 2023-04-18 14:12 UTC
Labels: bug, needs investigation

**Comment by endolith** [comment] 2023-04-22 11:10
8191 is Ada embeddings which is not fixed yet

**Comment by DeepDissect** [comment] 2023-04-29 00:21
Just leaving this comment for anyone encountering the same error. I literally just used one of the goals and said "No matter what, never ever exceed 8000 tokens as this will result in an API error. Summarize in smaller chunks if necessary". And now it's doing that and being very careful not to go over that.

Example output:

"CRITICISM:  I need to make sure to stay within the 8000 token limit when analyzing the code."

**Comment by endolith** [comment] 2023-04-29 03:05
```
  File "/sam/Auto-GPT/autogpt/agent/agent.py", line 170, in start_interaction_loop
    self.memory.add(memory_to_add)
  File "/sam/Auto-GPT/autogpt/memory/redismem.py", line 94, in add
    vector = create_embedding_with_ada(data)
```

This is what I tried to fix in https://github.com/Significant-Gravitas/Auto-GPT/pull/2039

**Comment by bruno90x** [comment] 2023-05-05 21:05
sorry guys you can set that on .env
