### ISSUE TITLE
Unresponsive at Enter Name

### ISSUE THREAD

**Issue by tylerlvance** [Significant-Gravitas/Auto-GPT#555] opened 2023-04-09 04:52 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I run main.py and prompt asks for a name, I enter a name and press enter, the command line drops but nothing happens

### Expected behavior 🤔

I thought it would log the name and continue on

### Your prompt 📝

tyler@DESKTOP-4DJ6SE2 MINGW64 ~/Auto-GPT (master)
$ python scripts/main.py
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: Super Assistant

**Comment by richbeales** [comment] 2023-04-09 06:28
Are you running the latest version from git? (git pull)

**Comment by tylerlvance** [comment] 2023-04-09 06:44
Yes, here is a recent interaction, the git pull seems to have bypassed the name section, still unresponsive when I input a command

![Capture](https://user-images.githubusercontent.com/130269267/230758582-96c091c6-6a63-4a09-903e-ff7124193f80.JPG)

**Comment by richbeales** [comment] 2023-04-09 06:56
Assuming your machine has an internet connection and the values in .env are correct, I'm not sure what's wrong here.  @Torantulino

**Comment by richbeales** [comment] 2023-04-09 07:11
Possible dupe of https://github.com/Torantulino/Auto-GPT/issues/522

**Comment by tylerlvance** [comment] 2023-04-09 23:01
Bumping, still an issue
![image](https://user-images.githubusercontent.com/130269267/230800449-4af60d5b-1b40-48e2-b81d-f36bb69625bc.png)

**Comment by Pwuts** [comment] 2023-04-18 02:26
Closing as resolved (based on #522). Please try the newest version and reopen if the problem persists.

**Closed by Pwuts** 2023-04-18 02:26 UTC
