### ISSUE TITLE
issues with chromium

### ISSUE THREAD

**Issue by ngmisl** [Significant-Gravitas/Auto-GPT#1853] opened 2023-04-16 11:19 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.reuters.com/finance/markets', 'question': 'Which industries performed well recently?'}
SYSTEM:  Command browse_website returned: Error: Message: unknown error: Chrome failed to start: exited normally. (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /snap/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Stacktrace: #0 0x55921de90fe3 <unknown> #1 0x55921dbcfd36 <unknown> #2 0x55921dbf8b20 <unknown> #3 0x55921dbf4a9b <unknown> #4 0x55921dc36af7 <unknown> #5 0x55921dc3611f <unknown> #6 0x55921dc2d693 <unknown> #7 0x55921dc0003a <unknown> #8 0x55921dc0117e <unknown> #9 0x55921de52dbd <unknown> #10 0x55921de56c6c <unknown> #11 0x55921de604b0 <unknown> #12 0x55921de57d63 <unknown> #13 0x55921de2ac35 <unknown> #14 0x55921de7b138 <unknown> #15 0x55921de7b2c7 <unknown> #16 0x55921de89093 <unknown> #17 0x7f330c094b43 <unknown>

### Current behavior 😯

It's opening the chromium browser, but does not pass it any data and just freezes then

### Expected behavior 🤔

work

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by p92** [comment] 2023-04-16 13:20
duplicate of #1757

**Closed** 2023-04-16 13:32 UTC
