### ISSUE TITLE
Mac open API key error communicating with openai

### ISSUE THREAD

**Issue by ethanye77** [Significant-Gravitas/Auto-GPT#1284] opened 2023-04-14 09:20 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ethanye/auto-GPT/scripts/main.py", line 461, in <module>
    main()
  File "/Users/ethanye/auto-GPT/scripts/main.py", line 365, in main
    assistant_reply = chat.chat_with_ai(
  File "/Users/ethanye/auto-GPT/scripts/chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/Users/ethanye/auto-GPT/scripts/llm_utils.py", line 28, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 529, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
bash-3.2$ 

after trying tons of ways, I could not solve this, somebody help!!!!! maybe when I am older it will all calm down but it is killing me now!

### Current behavior 😯

can't link to open ai API

### Expected behavior 🤔

sua~~~
and it link the API super quickly

### Your prompt 📝

```yaml
# Paste your prompt here
```
Last login: Fri Apr 14 17:07:53 on ttys002
(base) ethanye@Ethans-MacBook-Pro ~ % bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ pip list | grep openai
openai                        0.27.4
bash-3.2$ cd auto-GPT/
bash-3.2$ python scripts/main.py
Welcome back!  Would you like me to return to being vri?
Continue with the last settings?
Name:  vri
Role:  web searcher
Goals: ['search the differences between GPT-4 barn newbing claude and Auto-GPT', 'make a comparison of them and make a form ', 'send the result to gmail:ethanye77@gmail.com', 'create a picture of AI astronaut rinding horse behind the form', 'send the form and picture to gmail:ehtanye77@gmail.com when finished']
Continue (y/n): y
Using memory of type: LocalCache
Traceback (most recent call last):
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/ethanye/anaconda3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/ethanye/anaconda3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/ethanye/anaconda3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/ethanye/anaconda3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/ethanye/anaconda3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/ethanye/anaconda3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ethanye/auto-GPT/scripts/main.py", line 461, in <module>
    main()
  File "/Users/ethanye/auto-GPT/scripts/main.py", line 365, in main
    assistant_reply = chat.chat_with_ai(
  File "/Users/ethanye/auto-GPT/scripts/chat.py", line 126, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "/Users/ethanye/auto-GPT/scripts/llm_utils.py", line 28, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/Users/ethanye/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 529, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
bash-3.2$

**Comment by iurp** [comment] 2023-04-21 06:04
got the same issue here. Anybody with a suggestion?

**Comment by Maziak2520** [comment] 2023-04-24 09:57
sam isssue. just thinking of it's api limitation on open api side? anyone tried to switch to 3.5?

**Comment by vinodkumartheking** [comment] 2023-04-24 09:59
By default, it points to 3.5 turbo only right @Maziak2520 
![image](https://user-images.githubusercontent.com/18139750/233964528-a2c31cd2-a8ca-4733-aa99-a64b58b4146d.png)
Did it work if, it is changed to just 3.5

**Comment by Maziak2520** [comment] 2023-04-24 10:38
I'm in believe it points to gpt-4 by default. Tried to change both to 3.5.. still testing..

**Comment by vinodkumartheking** [comment] 2023-04-26 09:56
Found the issue of it, It is mainly related to the openApi key used , under free tier the limits is expired.
Check on the hits and limits on the keys. 
After creating a new account and key, it is working fine.

**Comment by ilove2git** [comment] 2023-04-26 13:11
> Found the issue of it, It is mainly related to the openApi key used , under free tier the limits is expired. Check on the hits and limits on the keys. After creating a new account and key, it is working fine.

i'm paid account and use new key created but still failed with same error.

**Comment by Pwuts** [comment] 2023-04-26 21:24
Duplicate of #2241

**Closed by Pwuts** 2023-04-26 21:24 UTC
Labels: API access
