### ISSUE TITLE
API Rate Limit Reached with new key

### ISSUE THREAD

**Issue by patrickelectric** [Significant-Gravitas/Auto-GPT#75] opened 2023-04-03 14:46 UTC
I just create a new key and it's failing to run:
```
Continue (y/n): y
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
```

![image](https://user-images.githubusercontent.com/1215497/229545231-7b463bc9-4630-45d5-a8cc-41df10e4e4be.png)

**Comment by Torantulino** [comment] 2023-04-03 14:50
Hu...
Never seen this one before.
Let me know if it's still happening after a in a few minutes?

I think this one is all on OpenAI, nothing I can really do.

**Comment by amrpyt** [comment] 2023-04-03 15:32
> 

I got The same Error

**Comment by dadhichi1** [comment] 2023-04-03 16:05
similar issue , any solve ?

**Comment by gaktug** [comment] 2023-04-03 16:28
Same issue with free account. API never used, but gives rate limit error.

**Comment by johanesPao** [comment] 2023-04-03 22:55
I think this one is on openai part. Last week I encountered the same error using openai module with new key that never been used before.

**Comment by matts8008** [comment] 2023-04-03 23:03
I'm having the same issue on a ChatGPT+ account. The API I am using says "Never" on when it was last used, but I'm not sure how often that is updated.

**Comment by matts8008** [comment] 2023-04-03 23:09
I found a solution. You need to add a billing credit card and then generate a new key.

1. Add a credit card to your OpenAI Account https://platform.openai.com/account/billing/overview
2. Generate new key
3. Everything works

Can someone please tell me how to make my Powershell terminal look pretty like the demo video in the Readme? 
I see codes like this

←[33mChatAI THOUGHTS: ←[0mI am starting by researching ways to 
←[33mREASONING: ←[0mThe first important step towards my main

**Comment by x-ili-x** [comment] 2023-04-05 04:37
I've done all the things and still run into this error. I have two credit cards on file. I don't have access to gpt4 API yet, but I'm trying to use 3.5 only mode. Tried in it's own environment and without.

Error:  API Rate Limit Reached. Waiting 10 seconds...
Traceback (most recent call last):
  File "J:\ai\auto-gpt\auto-gpt\scripts\chat.py", line 110, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "J:\ai\auto-gpt\auto-gpt\scripts\llm_utils.py", line 9, in create_chat_completion
    response = openai.ChatCompletion.create(
  File "C:\Users\mycon\miniconda3\envs\textgen\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\mycon\miniconda3\envs\textgen\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\mycon\miniconda3\envs\textgen\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\mycon\miniconda3\envs\textgen\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\mycon\miniconda3\envs\textgen\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\ai\auto-gpt\auto-gpt\scripts\main.py", line 287, in <module>
    assistant_reply = chat.chat_with_ai(
  File "J:\ai\auto-gpt\auto-gpt\scripts\chat.py", line 128, in chat_with_ai
    time.sleep(10)
KeyboardInterrupt

**Comment by Oxidiu** [comment] 2023-04-05 10:50
I am have the same issue on free OpenAI Account

Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...

... :( I was so excited to try this tool

**Comment by gourcetools** [comment] 2023-04-06 00:32
Same, new key

**Comment by gourcetools** [comment] 2023-04-06 00:50
Fixed: **Even if you are gpt+ you need to add a card to get a working key. demo keys dont work.**

**Comment by silverjoshi** [comment] 2023-04-06 04:39
facing the same issue. Don't free account keys work? Or do we need to add card even for free account and regenerate the API keys?

**Comment by silverjoshi** [comment] 2023-04-06 06:22
Check this answer -> https://stackoverflow.com/a/75898717

So apparently, it's openai that's making it hard to access via api codes, I am not liking this.

I get same the error 'openai.error.RateLimitError' when I tried running a prompt using python, it's openai that's restricting the accesses with randomly updated terms, no fault of Auto-GPT
Don't think there is a way around this, apart from creating a new openai account with a different phone number and using that api key

**Comment by x-ili-x** [comment] 2023-04-11 01:52
Fuggit. I've tried everything. OpenAI claims ignorance to what is happening. Incredibly frustrating. I was onto something meaningful and important for the first time in as long as I can remember, now it's not even worth doing because my peers left me in the dust on it.

**Comment by PundirShivam** [comment] 2023-04-11 09:41
Added payment . Fixed the problem. Apparently it is not working on free tier anymore, at least for me, even though its my first try. Kudos for those who got it working for free.

**Comment by gourcetools** [comment] 2023-04-11 18:45
Can someone close this?
=============== READ THIS ==================
**Even if you are gpt+ you need to add a card to get a working key. 
Free/demo keys dont work.**
=============== READ THIS ==================

**Comment by x-ili-x** [comment] 2023-04-11 19:00
**I have 3 cards on file.**

**Comment by nainesh-khanjire** [comment] 2023-04-12 14:10
not working for me, tried in replit ide same error continues

**Comment by JuroOravec** [comment] 2023-04-14 11:31
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @patrickelectric would you close this one issue if it indeed is the same thing?

(I had this issue too - It's that we haven't [opted into "paid account" on OpenAI's billing page](https://platform.openai.com/account/billing/overview))

I'm making an MR as we speak to update the README section on OpenAI's API key, to make this clear.

**Closed** 2023-04-16 08:16 UTC
