### ISSUE TITLE
File Operation Logger breaks incremental changes

### ISSUE THREAD

**Issue by rubberfashion** [Significant-Gravitas/Auto-GPT#2239] opened 2023-04-17 20:43 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Write a novel.
Create for each chapter a seperate txt file.
After a while generating several ideas, AutoGPT want to delete chapter file or outlines.

### Current behavior 😯

When AutoGPT want to delete a file he succeed.
It is logged in File Operation Logger.
But when AutoGPT want to create the file again with same filename it fails.

### Expected behavior 🤔

When AutoGPT want to delete a file he succeed.
It is logged in File Operation Logger.
The content of the file logger should also flush the name of the deleted file.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment] 2023-04-17 21:05
I was wondering about the purpose of that file... it is not cleaned on restart, so if you try to write a file with the same name as a day ago it will fail. Seems like the implementation is not optimal, not to mention that it is full with "append: file_logger.txt".

**Comment by rubberfashion** [comment] 2023-04-18 05:49
I was using the master branch and the "append: file_logger.txt" does not appear.
The only problem is when AutoGPT wants to delete a file that it has previously created or modified. The file cannot be created again because it is already in the logger, provided that the filename selected by AutoGPT is the same.

**Comment by Pwuts** [comment] 2023-04-18 16:47
Closing as duplicate of #1891

**Closed by Pwuts** 2023-04-18 16:47 UTC
