### ISSUE TITLE
Please add Open-Assistant 

### ISSUE THREAD

**Issue by paulVu** [Significant-Gravitas/Auto-GPT#639] opened 2023-04-10 03:35 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

https://github.com/LAION-AI/Open-Assistant
what do you think about that?

### Examples 🌈

a very promising open-source ChatGPT competitor 

### Motivation 🔦

Shout out to Open Assistant, a free and open source alternative to ChatGPT! 😎

**Comment by aodrasa** [comment] 2023-04-10 04:15
Open Assistance is nowhere near as capable as gpt-3.5 lol. Don't even bother.

**Comment by onekum** [comment] 2023-04-10 06:22
Maybe keep this open as an issue or a draft pull request for in the future when Open Assistant is actually capable enough. It's promising, but really not there yet.

**Comment by Wladastic** [comment] 2023-04-10 11:37
Checkout Vicuna.
Works much better than open assistant i guess.

**Comment by IsleOf** [comment] 2023-04-11 10:21
How about using vicuna and chatgpt to autogpt-train open assistant?

**Comment by IsleOf** [comment] 2023-04-11 10:36
https://chat.lmsys.org/

**Comment by kovenz0r** [comment] 2023-04-12 02:50
I believe the point of open assistant is for an uncensored model, which vicuna and gpt are not

**Comment by IsleOf** [comment] 2023-04-12 05:13
Koala gets closer, definitely needs extra training on darknet forums and marketplaces to spice it up for your special needs.

**Comment by kovenz0r** [comment] 2023-04-12 06:03
You know things are going well when you need to go to the "darknet" to learn that gender isn't a spectrum.

**Comment by Pwuts** [comment] 2023-04-18 03:25
Duplicate of #25, please add to that issue

**Closed by Pwuts** 2023-04-18 03:25 UTC

**Comment by ravitejachillara** [comment] 2023-04-25 09:06
> Open Assistance is nowhere near as capable as gpt-3.5 lol. Don't even bother.

When even chat GPT  started early it was not capable, slow and steadily it covered the market, may be Open Assistant will do the same only time will tell
