### ISSUE TITLE
Command browse_website returned: Error: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_112.0.5615 (C aused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by z-x-x136** [Significant-Gravitas/Auto-GPT#1803] opened 2023-04-16 07:09 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I used vpm throughout the process.vpm is normal.

I tried setting environment variables.
![微信截图_20230416122311](https://user-images.githubusercontent.com/87004536/232279075-ac8756c4-d77f-4f1e-ba4f-73cd70be259e.png)

I experimented with modifying the source code to add proxies.
![微信截图_20230416135720](https://user-images.githubusercontent.com/87004536/232279110-c4da42ea-546d-42a6-8157-5b611ec7f51e.png)

set http_proxy = 127.0.0.1:33210
set https_proxy = 127.0.0.1:33210
python -m autogpt --gpt3only
I tried setting  it.

### Current behavior 😯

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.bing.com', 'question': 'neural text generation auto-gpt'}

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 112.0.5615
[WDM] - Get LATEST chromedriver version for 112.0.5615 google-chrome
SYSTEM:  Command browse_website returned: Error: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_112.0.5615 (C
aused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
ZENG THOUGHTS:  Since the 'browse_website' command didn't work, we should try another approach to find resources on auto-gpt. One alternative way is to browse through academic resource
s on arXiv or other similar websites, which are more likely to contain information about AI. We could also try the 'google' command with more specific queries to find articles on auto-
gpt.
REASONING:  By exploring academic resources or using more specific search terms, we can find more reliable and comprehensive information about auto-gpt. These resources may give us acc
ess to cutting-edge research and expert opinions on the topic.
PLAN: 
-  Use the 'google' command with more specific queries to search for articles on auto-gpt.\n- Navigate to academic resources such as arXiv and browse through papers related to auto-gpt
.\n- Save any relevant information in a text file.
CRITICISM:  We still need to be critical of the sources and information we find. It's important to evaluate and cross-reference information from multiple sources to ensure its accuracy
 and reliability.
Attempting to fix JSON by finding outermost brackets 
Apparently json was fixed

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by hemangjoshi37a** [comment] 2023-04-16 11:54
This error can be caused by SSL issues with the host 'chromedriver.storage.googleapis.com'. One possible solution is to try setting HTTP and HTTPS proxy variables in the command prompt using the following commands:

set http_proxy=127.0.0.1:33210
set https_proxy=127.0.0.1:33210

Then run the 'autogpt' command again. If this does not work, you can try browsing academic resources such as arXiv to find information on auto-gpt or use the 'google' command with more specific queries to search for relevant articles. It is important to be critical of the sources and information found, and to cross-reference information from multiple sources to ensure accuracy and reliability.

**Comment by Pwuts** [comment] 2023-04-19 22:48
This is probably resolved by now. If not, feel free to reopen the issue.

**Closed by Pwuts** 2023-04-19 22:48 UTC
