### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 48 (char 1008)

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Significant-Gravitas/Auto-GPT#3679] opened 2023-05-02 10:36 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

sudo python3 -m autogpt  --continuous --gpt3only
y

### Current behavior 😯

NEXT ACTION:  COMMAND = improve_code ARGUMENTS = {'suggestions': ['Remove variable message since it is not used.', 'Provide more context to the purposes of the code.', 'Provide more information about the GPTAgent class and sendMessage method.', 'Provide more context to the expected behavior of the code.'], 'code': 'String message = "Hello Spring Agent";\nAgent agent = GPTAgent.getAgent();\nagent.sendMessage(message);\n'}
SYSTEM:  Command improve_code returned: # Improved code with the given suggestions # Removed unused variable message # Added comments to provide context and expected behavior # Added docstrings to provide information about the GPTAgent class and sendMessage method from typing import List def generate_improved_code(suggestions: List[str], code: str) -> str: # Provide more context to the purposes of the code. # This code sends a message to a GPTAgent using the sendMessage method # Provide more information about the GPTAgent class and sendMessage method. """ The GPTAgent class is a class that represents an agent that can communicate with the GPT-3 API. The sendMessage method is a method of the GPTAgent class that sends a message to the GPT-3 API. """ # Provide more context to the expected behavior of the code. # The expected behavior of this code is to send the message "Hello Spring Agent" to the GPT-3 API using the GPTAgent class. # Removed unused variable message agent = GPTAgent.getAgent() agent.sendMessage("Hello Spring Agent")
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/Auto-GPT/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/home/user/Auto-GPT/autogpt/main.py", line 157, in run_auto_gpt
    agent.start_interaction_loop()
  File "/home/user/Auto-GPT/autogpt/agent/agent.py", line 94, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/home/user/Auto-GPT/autogpt/llm/chat.py", line 166, in chat_with_ai
    agent.summary_memory = update_running_summary(
  File "/home/user/Auto-GPT/autogpt/memory_management/summary_memory.py", line 76, in update_running_summary
    content_dict = json.loads(event["content"])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 48 (char 1008)

### Expected behavior 🤔

proper work

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by k-boikov** [comment] 2023-05-02 22:42
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/3672

**Closed by k-boikov** 2023-05-02 22:42 UTC
