### ISSUE TITLE
add support for open-assistant.io 

### ISSUE THREAD

**Issue by seczoid** [Significant-Gravitas/Auto-GPT#853] opened 2023-04-11 20:35 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

add support to use https://open-assistant.io/ with openai so rate limits and money is no longer an issue

**Comment by Pwuts** [comment] 2023-04-18 03:21
Closing as duplicate of #639

**Closed by Pwuts** 2023-04-18 03:21 UTC
