### ISSUE TITLE
Invalid JSON loop

### ISSUE THREAD

**Issue by RowanFN** [Significant-Gravitas/Auto-GPT#751] opened 2023-04-11 00:56 UTC
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I just start the AI with its goals, and it'll happen shortly after starting or instantly. I have tried Parsing json fixes, other attempts, reinstalled, brand new install, in the goal asked to remember to answer in json. cannot get it to work now on anything.

I am running on continuous mode at the moment, to see how long and if it does what I'm after well, when the error will pop up.

Essentially it should search the internet, gather info, write it to a file. error shows and the loops this error during some process of browsing the internet and getting information.

### Current behavior 😯

SYSTEM:  Command browse_website returned: _(text stuff)_
Error: INVALID JSON
_'{attempted json I guess}'_
NEXT ACTION:  COMMAND = Error: ARGUMENTS = Invalid JSON
SYSTEM:  Command Error: threw the following error: Invalid JSON

forever looping

### Expected behavior 🤔

Write to file, or browse information on the internet etc

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Higgins4k** [comment] 2023-04-11 01:01
Are you using GPT 3 or 4?

**Comment by RowanFN** [comment] 2023-04-11 01:08
> Are you using GPT 3 or 4?

I don't have access to 4 I believe so using 3 I'd guess

**Comment by mencelot** [comment] 2023-04-11 01:26
Using 3.5. Used a fix I saw in previous post but it still goes off the rails after a while.

**Comment by dirgocs** [comment] 2023-04-11 01:41
I'm getting the same error. How did you fix it?

**Comment by Higgins4k** [comment] 2023-04-11 01:57
> Using 3.5. Used a fix I saw in previous post but it still goes off the rails after a while.



> I'm getting the same error. How did you fix it?



> Using 3.5. Used a fix I saw in previous post but it still goes off the rails after a while.

Using GPT 3 or 3.5 has issues with Json Parsing as autogpt uses GPT 4's method

**Comment by xXxFall3nxXx** [comment] 2023-04-11 07:36
![Screenshot 2023-04-11 153355](https://user-images.githubusercontent.com/128863850/231089019-68844648-1e74-49ce-b67a-95d009e30f8c.png)

I think the issue is when autogpt reads a string response and when it tries to create it to json it gets multiple quotes.
the parsing is wrong, I guess this issue would be resolved with escape characters during parsing the response autogpt is getting?

**Comment by RowanFN** [comment] 2023-04-11 09:17
> ![Screenshot 2023-04-11 153355](https://user-images.githubusercontent.com/128863850/231089019-68844648-1e74-49ce-b67a-95d009e30f8c.png)
> 
> I think the issue is when autogpt reads a string response and when it tries to create it to json it gets multiple quotes. the parsing is wrong, I guess this issue would be resolved with escape characters during parsing the response autogpt is getting?

This is the issue I'm having. Thought white text section is a bit different.

No idea on how to fix it, tried other prompts.txt fixes and aiming to tell it to be in JSON format in goals and such.

Error occurred when I updated the repository and seems it's forever there now.

**Comment by RowanFN** [comment] 2023-04-11 10:03
> > > ![Screenshot 2023-04-11 153355](https://user-images.githubusercontent.com/128863850/231089019-68844648-1e74-49ce-b67a-95d009e30f8c.png)
> > > I think the issue is when autogpt reads a string response and when it tries to create it to json it gets multiple quotes. the parsing is wrong, I guess this issue would be resolved with escape characters during parsing the response autogpt is getting?
> > 
> > 
> > This is the issue I'm having. Thought white text section is a bit different.
> > No idea on how to fix it, tried other prompts.txt fixes and aiming to tell it to be in JSON format in goals and such.
> > Error occurred when I updated the repository and seems it's forever there now.
> 
> I read in other posts and saw there was a update. I downloaded the whole thing as a zip just to be sure. This error doesnt happen anymore and is now replaced with this one everytime I ask it something related to reading a folder (sofar).
> 
> SYSTEM: Human feedback: I don't see the files you created. What is your working directory? Error: Traceback (most recent call last): File "/Users/******Desktop/Auto-GPT-master/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/Users/******/Desktop/Auto-GPT-master/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found NEXT ACTION: COMMAND = Error: ARGUMENTS = substring not found
> 
> It also seems to be hallucinating that it is performing actions in those folders. Like making a file and filling it with data. No problems browsing the web tho.
> 
> Also of note I feel like the Open AI API rate has been adjusted after lasts night little outage. I am hitting the limit (rate exceeded) far more often yesterday. I think this might be affecting things GPT3 side. Makes it hard to evaluate.

When did you update? Cause I did yesterday and from it came the error I stated above, I pulled from the repository, downloaded zip and overwrite/new folder etc. Everything I could think of.

**Comment by mencelot** [comment] 2023-04-11 10:16
> > > > ![Screenshot 2023-04-11 153355](https://user-images.githubusercontent.com/128863850/231089019-68844648-1e74-49ce-b67a-95d009e30f8c.png)
> > > > I think the issue is when autogpt reads a string response and when it tries to create it to json it gets multiple quotes. the parsing is wrong, I guess this issue would be resolved with escape characters during parsing the response autogpt is getting?
> > > 
> > > 
> > > This is the issue I'm having. Thought white text section is a bit different.
> > > No idea on how to fix it, tried other prompts.txt fixes and aiming to tell it to be in JSON format in goals and such.
> > > Error occurred when I updated the repository and seems it's forever there now.
> > 
> > 
> > I read in other posts and saw there was a update. I downloaded the whole thing as a zip just to be sure. This error doesnt happen anymore and is now replaced with this one everytime I ask it something related to reading a folder (sofar).
> > SYSTEM: Human feedback: I don't see the files you created. What is your working directory? Error: Traceback (most recent call last): File "/Users/******Desktop/Auto-GPT-master/scripts/main.py", line 76, in print_assistant_thoughts assistant_reply_json = fix_and_parse_json(assistant_reply) File "/Users/******/Desktop/Auto-GPT-master/scripts/json_parser.py", line 51, in fix_and_parse_json brace_index = json_str.index("{") ValueError: substring not found NEXT ACTION: COMMAND = Error: ARGUMENTS = substring not found
> > It also seems to be hallucinating that it is performing actions in those folders. Like making a file and filling it with data. No problems browsing the web tho.
> > Also of note I feel like the Open AI API rate has been adjusted after lasts night little outage. I am hitting the limit (rate exceeded) far more often yesterday. I think this might be affecting things GPT3 side. Makes it hard to evaluate.
> 
> When did you update? Cause I did yesterday and from it came the error I stated above, I pulled from the repository, downloaded zip and overwrite/new folder etc. Everything I could think of.

A few hours ago. Honestly just download a brand new copy and copy over your .env settings making sure to notice slight differences between the versions. Asides from that the whole things takes seconds to resetup.

**Comment by thomasmunoz** [comment] 2023-04-11 11:04
did someone managed to fix this ? I have the same think, it keeps looping forever 
I'm using GPT4

**Comment by MrXandbadas** [comment] 2023-04-14 11:39
Hello!, Pulled Through the newest codebase and attempted to use this and was given the following
(For context I am trying to get it to read Arduino Code)

```
Attempting to fix JSON by finding outermost brackets 
Apparently json was fixed. 
Error:
  Traceback (most recent call last):
  File "G:\NewCode2023\AutoGPT_test\Auto-GPT\scripts\main.py", line 89, in print_assistant_thoughts
    assistant_thoughts = assistant_reply_json.get("thoughts", {})
AttributeError: 'str' object has no attribute 'get'

Attempting to fix JSON by finding outermost brackets 
Apparently json was fixed. 
  Warning: Failed to parse AI output, attempting to fix.
 If you see this warning frequently, it's likely that your prompt is confusing the AI. Try changing it up slightly.
Failed to fix AI output, telling the AI. 
```

**Comment by p-i-** [comment] 2023-04-14 22:44
Community effort to sort out this JSON fail once and for all at https://github.com/Torantulino/Auto-GPT/issues/1407

We have 17 open PRs for fixing this, and the merge-team are stacked.

**Comment by Pwuts** [comment] 2023-04-18 04:36
Closing as one of many duplicates; superseded by #1407

**Closed by Pwuts** 2023-04-18 04:36 UTC
Labels: invalid_json
