### ISSUE TITLE
Fatal error reading JSON

### ISSUE THREAD

**Issue by jcoon-icapitalnetwork** [Significant-Gravitas/Auto-GPT#4052] opened 2023-05-09 12:59 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Stack trace of the error. The error handling should allow for a graceful fail that allows AutoGPT to continue. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 186, in run_auto_gpt
    agent.start_interaction_loop()
  File "/app/autogpt/agent/agent.py", line 113, in start_interaction_loop
    assistant_reply = chat_with_ai(
  File "/app/autogpt/llm/chat.py", line 165, in chat_with_ai
    agent.summary_memory = update_running_summary(
  File "/app/autogpt/memory_management/summary_memory.py", line 78, in update_running_summary
    content_dict = json.loads(event["content"])
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 13 column 9 (char 874)
ERROR: 1

### Current behavior 😯

Exit on error. 

### Expected behavior 🤔

Graceful fail on error.

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by yhyu13** [comment] 2023-05-09 17:17
@ALL need help with this error, it is annoying, can't even make gpt read local file?!

**Comment by JKrueckl** [comment] 2023-05-09 20:47
> @ALL need help with this error, it is annoying, can't even make gpt read local file?!

Have you tried using double quotes instead of single quotes in your arguments JSON object?

Something like this might do the trick:
"{\"filename\": \"/home/hangyu5/Documents/Git-repoMy/AIResearchVault/repo/LLMApp/Auto-GPT/autogpt/auto_gpt_workspace/hash-grid-encoding/train.py\"}"

**Comment by GoZippy** [comment] 2023-05-09 21:48
Hey posting you need help after reporting an issue is not going to do much for anyone... I suggest looking through all the other similar issue posts and the DISCUSSIONS pages... this is a known issue and if you read any of the other threads you will get a sense of the work-arounds that were given and ways to change prompt to request only json responses... anyhow - read first is my help for you right now. There are indeed many similar threads already - no need to start another.

**Comment by XaviscoB** [comment] 2023-05-09 22:32
I'm having a similar problem, program runs normally when I stop this error

**Comment by suparious** [comment] 2023-05-09 23:31
I get this error all the time, tried several different python versions, but it seems that there is some hallucination from gpt 3.5 that creates bad JSON, then the program crashes with that error, or similar with json.decoder.JSONDecodeError getting pissed off.

**Comment by GoZippy** [comment] 2023-05-10 01:10
guys - have any of you searched the current and all issues for this? A quick search shows lots of threads on this same topic... no need to add new issues... look at the different ways and work arounds that are already posted...

**Comment by yhyu13** [comment] 2023-05-10 05:41
> guys - have any of you searched the current and all issues for this? A quick search shows lots of threads on this same topic... no need to add new issues... look at the different ways and work arounds that are already posted...

Yep, but none is solved? https://github.com/Significant-Gravitas/Auto-GPT/issues/21

**Comment by yhyu13** [comment] 2023-05-10 05:42
Microsoft/Github probably need an AI to automatically reply issue/bug repot/erro with best fitting history answers, so that we do have to repetivively search issues/discussions all the time

**Comment by anonhostpi** [comment] 2023-05-12 07:39
Duplicate of the various JSONDecodeError bugs coming from summary_memory.py. Marking as duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/3716

See: https://github.com/anonhostpi/AUTOGPT.TRACKERS/blob/main/TOPICS/0017.BUGS/JSON.md

**Closed by anonhostpi** 2023-05-12 07:39 UTC
Labels: invalid_json

**Comment by suparious** [comment] 2023-05-13 03:11
Possibly fixed in Fixed with in #3996
