### ISSUE TITLE
Response keeps being : NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}

### ISSUE THREAD

**Issue by shFrank** [Significant-Gravitas/Auto-GPT#2364] opened 2023-04-18 10:26 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Ask to make a cost estimate for a trip. It will start to use Google and other resources to find the prices. But before he could combine all this information together into a total cost, the response begins to be NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}. The plans it provides were still logical.

I tried both stable and master, both have the same issue.

### Current behavior 😯

After a few steps, Auto-GPT will provide plans as usual but the NEXT ACTION will always be  COMMAND = do_nothing ARGUMENTS = {}

It will keep saying "I need to be careful to gather accurate and up-to-date information to ensure the estimate is as accurate as possible."

Even if you input just follow the plan the response will still be the same.
<img width="620" alt="Screenshot 2023-04-18 at 6 21 11 PM" src="https://user-images.githubusercontent.com/45113795/232748396-11b8b135-dc27-4a95-bdd6-650ea608f001.png">

<img width="928" alt="Screenshot 2023-04-18 at 6 13 51 PM" src="https://user-images.githubusercontent.com/45113795/232747157-a7257504-40b8-4936-a292-e134463f9b70.png">

### Expected behavior 🤔

Follow the plan and calculate the total estimate

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by k-boikov** [comment] 2023-04-18 10:34
Possibly LLM limitation of GPT-3.5. You need to change your prompt.

**Comment by k-boikov** [comment] 2023-04-18 10:36
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/2023

**Comment by Alexander220799** [comment] 2023-04-18 13:26
Same Problem here.

**Comment by Pwuts** [comment] 2023-04-18 14:13
Closing as duplicate of #2023

**Closed by Pwuts** 2023-04-18 14:13 UTC
