### ISSUE TITLE
The script shows me the error The JSON object is invalid

### ISSUE THREAD

**Issue by RomeoJuank** [Significant-Gravitas/Auto-GPT#2266] opened 2023-04-17 23:29 UTC
![image](https://user-images.githubusercontent.com/109975936/232632201-55d1ce4e-e549-44ca-8fec-daefbe73d095.png)

**Comment by k-boikov** [comment] 2023-04-17 23:31
Duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/21
TLDR - LLMs are not good at following strict orders how to format their answers (yet).

**Comment by Pwuts** [comment] 2023-04-17 23:32
Closing as duplicate

**Closed by Pwuts** 2023-04-17 23:32 UTC
