### ISSUE TITLE
Error: API Rate Limit Reached. Waiting ten seconds...

### ISSUE THREAD

**Issue by AuroraHolding** [Significant-Gravitas/Auto-GPT#235] opened 2023-04-05 05:39 UTC
![Screenshot 2023-04-05 013834](https://user-images.githubusercontent.com/122390212/229990521-4144666f-bed8-4aab-86e0-87e554d8e52f.png)
![Screenshot 2023-04-05 013834](https://user-images.githubusercontent.com/122390212/229990559-0e74284d-649e-44f9-b841-e8010055f011.png)

**Comment by Provello** [comment] 2023-04-05 06:55
https://platform.openai.com/docs/guides/rate-limits

Also worth checking: https://platform.openai.com/account/usage

Check firstly if your usage limits are being hit because if you're processing a lot of tokens

**Comment by RichardAtCT** [comment] 2023-04-05 07:22
Have you exported your private keys? Fixed it for me!

**Comment by m4ntr4r4m4** [comment] 2023-04-05 14:11
I have the same problem.

**Comment by dzovani** [comment] 2023-04-05 19:15
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 1

same problem, not using api for anything else besides this app

**Comment by m4ntr4r4m4** [comment] 2023-04-06 00:15
i just fixed it. check your free usage if it 's expired. in this link : https://platform.openai.com/account/usage

**Comment by gourcetools** [comment] 2023-04-06 00:50
Fixed: **Even if you are gpt+ you need to add a card to get a working key. demo keys dont work.**

**Comment by abhaykhawas** [comment] 2023-04-06 02:03
I have noticed when I use OPENAI_API_KEY from one of my account it works but for other account it doesn't for some reason.

**Comment by justani** [comment] 2023-04-07 05:45
This happened with me as well. I fixed by manually adding `openai.organization=<my-org-id>` in `llm_utils.py`. The rate limit error was coming because I had two organizations in my account and the API was somehow calling for the organization which doesn't have billing set. 

Another option can be to update the default organization from [here](https://platform.openai.com/account/api-keys).

**Comment by WillBeebe** [comment] 2023-04-07 15:30
The `.env` file is missing `OPENAI_ORGANIZATION_ID`. Add that to your environment and it solves this problem. 👍

**Comment by JuroOravec** [comment] 2023-04-14 11:34
Duplicate of https://github.com/Torantulino/Auto-GPT/issues/1189. @AuroraHolding would you close this one issue if it indeed is the same thing?

(I had this issue too - It's that we haven't [opted into "paid account" on OpenAI's billing page](https://platform.openai.com/account/billing/overview))

I'm making an MR as we speak to update the README section on OpenAI's API key, to make this clear.

**Closed** 2023-04-16 09:22 UTC
