### ISSUE TITLE
This model maxium context length is 8191 tokens - trown out of the program

### ISSUE THREAD

**Issue by Blackbrain63** [Significant-Gravitas/Auto-GPT#2337] opened 2023-04-18 07:53 UTC
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [x] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

read text file that contains more characters that the 8191 tokes

### Current behavior 😯

Python\Python311\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 8938 tokens (8938 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by E-Labs-io** [comment] 2023-04-18 10:05
I have been getting this too.  When it tried to read form a large file it doesn't break down into chunks before trying to process so seems that the GPT engineer rejects for being too large.  Maybe a break to chunks function between read and injest/send to GPT

**Comment by marktsears** [comment] 2023-04-18 11:44
Yes, getting the same and that is what is needed

**Comment by Pwuts** [comment] 2023-04-18 13:12
Closing as duplicate of #796

**Closed by Pwuts** 2023-04-18 13:12 UTC
Labels: needs investigation

**Comment by hanskraut31312312** [comment] 2023-04-21 21:18
me to happened since the first days. Im on stable this is 90% if crashes. 3.5t Stable version 

NEXT ACTION:  COMMAND = search_files ARGUMENTS = {'directory': '.', 'query': 'cassandra_installation.sh'}
->
openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 157088 tokens (157088 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.
-> 
crash
