### ISSUE TITLE
ASK HUMAN FOR HELP

### ISSUE THREAD

**Issue by horazius** [Significant-Gravitas/Auto-GPT#2460] opened 2023-04-18 22:31 UTC
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Ask Human for help on Twitter in the first version. Later via email if we give him the credentials and write also the email command. And finally to post something on stackoverflow and reddit. Maybe also on other channels. This would combine human intelligence with ai. 

We should just add this feature after a long time of no results. Therefore we could search on the net for an expert for that topic on twitter, then on linked in and then somewhere else in the net.

### Motivation 🔦

If Auto-GPT has an impossible problem like a captcha or something else ChatGPT couldn't help this would bring a soltution and combines ai with hi.

**Comment by Notarin** [comment] 2023-04-19 06:17
Hi! Maybe instead for starters we could have a simple command that simply pauses execution requesting human input? This is fairly simple and I'd say it could potentially be marked as essential opening the doorway for it being implemented.

**Comment by IsleOf** [comment] 2023-04-19 07:26
Some kind of automated self evaluation for it's limitations is needed, for example hitting the moral wall, then asking for human intervention when model refuses to take a side, for example sticking to concept that gender is spectrum, but duality is needed for medical research.

**Comment by Notarin** [comment] 2023-04-19 09:03
I understand what you're saying, but I seriously doubt that the dev team will mark it as "Essential"

**Comment by ntindle** [comment] 2023-04-20 07:32
potential duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/150, https://github.com/Significant-Gravitas/Auto-GPT/issues/1472

**Comment by ntindle** [comment] 2023-04-21 04:08
potential duplicate of https://github.com/Significant-Gravitas/Auto-GPT/issues/150, https://github.com/Significant-Gravitas/Auto-GPT/issues/1472

**Closed by ntindle** 2023-04-21 04:08 UTC
